echo "1. Add 'autoTune' to parameterDescriptors in RubberBandProcessor"
echo "2. Add 'autoTune' to src/types.ts (export interface SynthParams & EffectsContextValue, export interface NoteProperties)"
echo "3. Add 'autoTune' to SamplerKnobControls.tsx and EffectsSendProperties.tsx"
echo "4. Add 'autoTune' in useSamplerPanelState.ts"
echo "5. Add 'autoTune' in playSamplerVoice.ts"
echo "6. Add 'autoTune' in effectsControl.ts (setWorkletParam)"
echo "7. In RubberBandProcessor, implement a zero-crossing period detector during the output retrieval loop (on the output buffer before applying other effects) to calculate detected frequency."
echo "8. Based on detected frequency, if autoTune > 0, quantize the frequency to nearest semitone, and modulate the rubberBand pitch shift or granular phase."
echo "Wait, RubberBand pitch shift is applied *before* output retrieval! We pass the pitch to RubberBand."
echo "So, pitch correction could be applied dynamically to the pitch multiplier passed to RubberBand, OR applied via a fast granular phase modulation (like a pitch shifter delay line) in the output path."
echo "But if we measure the pitch on the output, we can't look ahead. If we measure it on the *input* buffer (during FREEZE stream), we can adjust RubberBand pitchScale."
echo "Wait, we just need zero-crossing detection. Let's do it on the output of the grains (before RubberBand)? Or maybe after RubberBand?"
echo "Let's read how RubberBand processor handles the input/output."
