/**
 * AI Song Importer Module
 * 
 * Import songs generated by external AI systems (Claude, Gemini, Jules, Copilot, etc.)
 * 
 * Usage:
 * ```typescript
 * import { 
 *   AISongImporter, 
 *   convertAISong, 
 *   parseAISongJSON,
 *   type AISongData 
 * } from './importers/ai-song';
 * 
 * // Parse JSON from AI
 * const parsed = parseAISongJSON(aiGeneratedJson);
 * if (parsed.success) {
 *   // Convert to Hyphon format
 *   const result = convertAISong(parsed.data);
 *   if (result.success) {
 *     loadSong(result.song);
 *   }
 * }
 * ```
 */

// Main importer
export { AISongImporter, convertAISong, parseAISongJSON } from './AISongImporter';

// Types
export type { 
  AISongData, 
  AITrackData, 
  AINoteEvent, 
  AISamplerBankData,
  AIImportResult,
  AIImportError,
  AIImportErrorDetails,
  AIImportReport
} from './AISongImporter';

// Re-export for convenience
export type { SavedSongData } from '../../types';
