/**
 * AI Song Importer Module
 * 
 * Import songs generated by external AI systems (Claude, Gemini, Jules, Copilot, etc.)
 * 
 * Usage:
 * ```typescript
 * import { 
 *   AISongImporter, 
 *   convertAISong, 
 *   parseAISongJSON,
 *   uploadAISong,
 *   type AISongData 
 * } from './importers/ai-song';
 * 
 * // Parse JSON from AI
 * const parsed = parseAISongJSON(aiGeneratedJson);
 * if (parsed.success) {
 *   // Convert to Hyphon format
 *   const result = convertAISong(parsed.data);
 *   if (result.success) {
 *     loadSong(result.song);
 *   }
 * }
 * 
 * // Upload to cloud with enhanced API
 * const uploadResult = await uploadAISong(aiData, hyphonSong, {
 *   folder: 'my-songs',
 *   tags: ['funky', 'bass']
 * });
 * if (uploadResult.success) {
 *   console.log('Uploaded to:', uploadResult.publicUrl);
 * }
 * ```
 * 
 * Storage Integration:
 * -------------------
 * The importer now uses AISongStorage for cloud operations, which provides:
 * - Auto-tagging with generator names (claude, gemini, etc.)
 * - Prompt storage in descriptions
 * - Version history tracking
 * - Folder organization for AI songs
 * - Enhanced error handling with retry logic
 * 
 * ```typescript
 * import { AISongStorage } from './services/AISongStorage';
 * 
 * // Get all AI songs
 * const songs = await AISongStorage.getAISongs();
 * 
 * // Search by prompt content
 * const results = await AISongStorage.searchAISongs('funky bass');
 * 
 * // Get version history
 * const versions = await AISongStorage.getAISongVersions('song-id');
 * ```
 */

// Main importer
export { 
  AISongImporter, 
  convertAISong, 
  parseAISongJSON,
  uploadAISong,
  isValidNote 
} from './AISongImporter';

// Automation utilities
export {
  validateAutomation,
  isValidAutomationTarget,
  convertAutomationToPoints,
  mapTargetToTrackKey,
  getAutomationSummary,
  getValidParametersForTarget,
  determinePatternLength,
  createEmptyAutomationLane,
  interpolateAutomation,
  VALID_AUTOMATION_TARGETS,
  VALID_PARAMETERS_BY_TARGET,
  VALID_INTERPOLATION_MODES,
  DEFAULT_PATTERN_LENGTH,
  MIDI_VALUE_RANGE,
  EXAMPLE_WITH_AUTOMATION,
  type AutomationValidationError,
  type AutomationValidationResult,
  type AutomationLaneSummary
} from './automation';

// Types from AISongImporter
export type { 
  AISongData, 
  AITrackData, 
  AINoteEvent, 
  AISamplerBankData,
  AIImportResult,
  AIImportError,
  AIImportErrorDetails,
  AIImportResultType,
  AIImportReport,
  AIUploadResult,
  AIUploadError,
  AIUploadResultType,
  // Automation types
  AIAutomationLane,
  AIAutomationTarget,
  AITargetedParameter,
  AIInterpolationMode,
  // Effects types
  AIEffectsChain,
  AIMasterEffects,
  AITrackEffects,
  AICompressorSettings,
  AIDistortionSettings,
  AIDelaySettings,
  AIReverbSettings,
  AIFilterSettings,
  AIChorusSettings,
  AIPhaserSettings,
  // Harmonizer types
  AIHarmonizerConfig,
  // Phoneme painter types
  AIPhonemePainterConfig,
  AIPhonemeMapping,
  // Internal types
  HyphonEffectsData,
  HyphonMasterEffects,
  HyphonTrackEffects,
  HyphonSong
} from './AISongImporter';

// AISongStorage for direct storage operations
export { 
  AISongStorage,
  AI_SONGS_FOLDER,
  AI_GENERATORS 
} from '../../services/AISongStorage';

// Types from AISongStorage
export type {
  AISongVersion,
  AISongMetadata,
  AISongSearchFilters,
  AISongUploadOptions,
  AIGenerator
} from '../../services/AISongStorage';

// Storage types
export type {
  StorageResult,
  UploadSuccess,
  StorageError,
  CloudSongMeta,
  CloudSongPayload,
  CloudItemType
} from '../../services/CloudStorage';

// Re-export for convenience
export type { SavedSongData } from '../../types';

// Example AI song with effects (for documentation/testing)
export const EXAMPLE_WITH_EFFECTS: AISongData = {
  meta: {
    title: "Space Acid",
    author: "AI Generator",
    version: "1.0",
    createdAt: new Date().toISOString(),
    generator: "claude-3-opus",
    prompt: "Generate a space acid techno track with effects",
    tags: ["techno", "acid", "space"]
  },
  globals: {
    tempo: 128,
    timeSignature: [4, 4]
  },
  tracks: {
    synthA: {
      notes: [
        { step: 0, note: "C3", velocity: 0.9, accent: true },
        { step: 4, note: "E3", velocity: 0.8 },
        { step: 8, note: "G3", velocity: 0.9, accent: true },
        { step: 12, note: "A#3", velocity: 0.8 }
      ],
      harmonizer: { 
        enabled: true, 
        voices: 3, 
        harmonyType: 'fifth', 
        formantShift: 0, 
        detune: 10,
        spread: 50
      }
    },
    sampler: [{
      bankIndex: 0,
      steps: [
        { step: 0, note: "C4", velocity: 1.0 },
        { step: 16, note: "C4", velocity: 1.0 }
      ],
      ttsText: "Cosmic voyager",
      phonemePainter: {
        enabled: true,
        text: "Cosmic voyager",
        mapping: [
          { step: 0, phoneme: "KO", pitch: "C4" },
          { step: 2, phoneme: "z", pitch: "E4" },
          { step: 4, phoneme: "m", pitch: "G4" },
          { step: 6, phoneme: "Ik", pitch: "C4" }
        ]
      }
    }]
  },
  effects: {
    master: { 
      reverb: { size: 70, decay: 2.5, mix: 30 } 
    },
    tracks: {
      synthA: { 
        delay: { time: 300, feedback: 40, mix: 25, pingPong: true } 
      },
      synthB: { 
        distortion: { type: 'soft', amount: 30 } 
      }
    }
  }
};
