/**
 * Compact CMU-dict subset for English G2P (ARPABET, no stress digits).
 * OOV words fall back to letter rules in g2p.ts.
 */
export const CMU_DICT: Record<string, readonly string[]> = {
  a: ['AH'],
  about: ['AH', 'B', 'AW', 'T'],
  ah: ['AA'],
  air: ['EH', 'R'],
  all: ['AO', 'L'],
  am: ['AE', 'M'],
  an: ['AE', 'N'],
  and: ['AH', 'N', 'D'],
  are: ['AA', 'R'],
  as: ['AE', 'Z'],
  at: ['AE', 'T'],
  away: ['AH', 'W', 'EY'],
  be: ['B', 'IY'],
  beat: ['B', 'IY', 'T'],
  because: ['B', 'IH', 'K', 'AO', 'Z'],
  been: ['B', 'IH', 'N'],
  but: ['B', 'AH', 'T'],
  by: ['B', 'AY'],
  can: ['K', 'AE', 'N'],
  come: ['K', 'AH', 'M'],
  could: ['K', 'UH', 'D'],
  day: ['D', 'EY'],
  do: ['D', 'UW'],
  down: ['D', 'AW', 'N'],
  ee: ['IY'],
  eh: ['EH'],
  every: ['EH', 'V', 'R', 'IY'],
  for: ['F', 'AO', 'R'],
  from: ['F', 'R', 'AH', 'M'],
  get: ['G', 'EH', 'T'],
  go: ['G', 'OW'],
  going: ['G', 'OW', 'IH', 'NG'],
  good: ['G', 'UH', 'D'],
  had: ['HH', 'AE', 'D'],
  has: ['HH', 'AE', 'Z'],
  have: ['HH', 'AE', 'V'],
  he: ['HH', 'IY'],
  hello: ['HH', 'AH', 'L', 'OW'],
  her: ['HH', 'ER'],
  here: ['HH', 'IY', 'R'],
  hi: ['HH', 'AY'],
  him: ['HH', 'IH', 'M'],
  his: ['HH', 'IH', 'Z'],
  how: ['HH', 'AW'],
  i: ['AY'],
  if: ['IH', 'F'],
  in: ['IH', 'N'],
  into: ['IH', 'N', 'T', 'UW'],
  is: ['IH', 'Z'],
  it: ['IH', 'T'],
  just: ['JH', 'AH', 'S', 'T'],
  know: ['N', 'OW'],
  like: ['L', 'AY', 'K'],
  little: ['L', 'IH', 'T', 'AH', 'L'],
  look: ['L', 'UH', 'K'],
  love: ['L', 'AH', 'V'],
  make: ['M', 'EY', 'K'],
  me: ['M', 'IY'],
  more: ['M', 'AO', 'R'],
  my: ['M', 'AY'],
  no: ['N', 'OW'],
  not: ['N', 'AA', 'T'],
  now: ['N', 'AW'],
  of: ['AH', 'V'],
  oh: ['OW'],
  on: ['AA', 'N'],
  one: ['W', 'AH', 'N'],
  oo: ['UW'],
  or: ['AO', 'R'],
  our: ['AW', 'ER'],
  out: ['AW', 'T'],
  over: ['OW', 'V', 'ER'],
  people: ['P', 'IY', 'P', 'AH', 'L'],
  said: ['S', 'EH', 'D'],
  see: ['S', 'IY'],
  she: ['SH', 'IY'],
  so: ['S', 'OW'],
  some: ['S', 'AH', 'M'],
  take: ['T', 'EY', 'K'],
  than: ['DH', 'AE', 'N'],
  that: ['DH', 'AE', 'T'],
  the: ['DH', 'AH'],
  their: ['DH', 'EH', 'R'],
  them: ['DH', 'EH', 'M'],
  then: ['DH', 'EH', 'N'],
  there: ['DH', 'EH', 'R'],
  they: ['DH', 'EY'],
  this: ['DH', 'IH', 'S'],
  time: ['T', 'AY', 'M'],
  to: ['T', 'UW'],
  up: ['AH', 'P'],
  us: ['AH', 'S'],
  want: ['W', 'AA', 'N', 'T'],
  was: ['W', 'AA', 'Z'],
  we: ['W', 'IY'],
  well: ['W', 'EH', 'L'],
  were: ['W', 'ER'],
  what: ['W', 'AH', 'T'],
  when: ['W', 'EH', 'N'],
  where: ['W', 'EH', 'R'],
  who: ['HH', 'UW'],
  will: ['W', 'IH', 'L'],
  with: ['W', 'IH', 'DH'],
  world: ['W', 'ER', 'L', 'D'],
  would: ['W', 'UH', 'D'],
  yes: ['Y', 'EH', 'S'],
  you: ['Y', 'UW'],
  your: ['Y', 'AO', 'R'],
};
