import { RingBuffer } from "../utils/ringBuffer";
import { ExpressiveVoiceProcessor } from "../engines/rubberband/ExpressiveVoiceProcessor";
import { WorkletPerfReporter } from "./workletPerfReporter";
// @ts-ignore - The file is generated by the build script
import createRubberBandModule from "./rubberband-lib.js";


interface AudioWorkletProcessor {
  readonly port: MessagePort;
  process(inputs: Float32Array[][], outputs: Float32Array[][], parameters: Record<string, Float32Array>): boolean;
}

declare var AudioWorkletProcessor: {
  prototype: AudioWorkletProcessor;
  new(options?: any): AudioWorkletProcessor;
};

declare function registerProcessor(name: string, processorCtor: (new (options?: any) => AudioWorkletProcessor)): void;

declare const globalThis: {
  sampleRate: number;
};

class RubberBandProcessor extends AudioWorkletProcessor {
  private rubberBand: any = null;
  private inputRingBuffer: RingBuffer | null = null;
  private outputRingBuffer: RingBuffer | null = null;
  private expressiveProcessor: ExpressiveVoiceProcessor;
  private readonly perf = new WorkletPerfReporter(this.port, 'rubberband');

  // WASM Memory Management
  private inputHeapPtr: number = 0;
  private outputHeapPtr: number = 0;
  private heapSizeFrames: number = 0;

  // Audio State
  private sampleRate = 44100;
  private initialized = false;
  private fullSampleBuffer: Float32Array | null = null;

  // Phoneme Data
  private phonemeData: Float32Array | null = null;
  private phonemeRatios: number[] | null = null;

  // Custom Grain Envelope
  private customGrainEnvelope: number[] | null = null;

  // Playback State (Unified)
  private isPlaying = false;
  private isReverse = false;
  private grains = [
    { phase: 0, start: 0, size: 0, active: false },
    { phase: 0, start: 0, size: 0, active: false }
  ];
  private customWindowShape: Float32Array | null = null;
  private freezeLfoPhase: number = 0;
  private grainLfoPhase: number = 0;
  private gatePhase: number = 0;
  private currentGateLfo: number = 1.0;

  // Spectral Compressor states (3-band SVF)
  private scState = {
    // SVF state: [lp, bp] per channel. We cascade for steeper slopes if needed, but simple is fine.
    // Actually for 3 bands we need 2 crossovers: Low/Mid and Mid/High
    // Low pass at ~300Hz, High pass at ~3kHz.
    // State for Linkwitz-Riley or SVF:
    lp1: [0, 0], bp1: [0, 0], // Crossover 1 (~300Hz) for L, R
    lp2: [0, 0], bp2: [0, 0], // Crossover 2 (~3kHz) for L, R

    // Envelopes for Low, Mid, High (Stereo linked: one per band)
    env: [0, 0, 0]
  };

  // Bitcrusher states
  private downsamplePhase: number[] = [0, 0];
  private lastSampleValue: number[] = [0, 0];

  // Spectral Compression states (3-band approximation)
  private scLow: number[] = [0, 0];
  private scMid: number[] = [0, 0];
  private scHigh: number[] = [0, 0];
  private scEnvLow: number[] = [0, 0];
  private scEnvMid: number[] = [0, 0];
  private scEnvHigh: number[] = [0, 0];

  // Grain Panning State
  private grainWrapPending = false;
  private wasFrozen = false;
  private grainPanL = [Math.SQRT1_2, Math.SQRT1_2, Math.SQRT1_2]; // Low, Mid, High
  private grainPanR = [Math.SQRT1_2, Math.SQRT1_2, Math.SQRT1_2];

  private currentSamplePtr = 0;
  private startSamplePtr = 0;
  private endSamplePtr = 0;
  private basePitch = 1.0;
  static get parameterDescriptors() {
    return [
      { name: 'pitchScale', defaultValue: 1.0, minValue: 0.1, maxValue: 4.0 },
      { name: 'timeRatio', defaultValue: 1.0, minValue: 0.1, maxValue: 4.0 },
      { name: 'vibratoDepth', defaultValue: 0.0, minValue: 0.0, maxValue: 1.0 },
      { name: 'vibratoRate', defaultValue: 5.0, minValue: 0.1, maxValue: 20.0 },
      { name: 'tremoloDepth', defaultValue: 0.0, minValue: 0.0, maxValue: 1.0 },
      { name: 'tremoloRate', defaultValue: 0.1, minValue: 0.1, maxValue: 20.0 },
      { name: 'gateDepth', defaultValue: 0.0, minValue: 0.0, maxValue: 1.0 },
      { name: 'gateRate', defaultValue: 4.0, minValue: 0.1, maxValue: 50.0 },
      { name: 'breathIntensity', defaultValue: 0.0, minValue: 0.0, maxValue: 1.0 },

      { name: 'pitchAttack', defaultValue: 0.0, minValue: 0.0, maxValue: 2.0 },
      { name: 'pitchDecay', defaultValue: 0.0, minValue: 0.0, maxValue: 2.0 },
      { name: 'pitchAmount', defaultValue: 0.0, minValue: -24.0, maxValue: 24.0 },
      { name: 'attack', defaultValue: 0.05, minValue: 0.001, maxValue: 2.0 },
      { name: 'decay', defaultValue: 0.1, minValue: 0.001, maxValue: 2.0 },
      { name: 'sustain', defaultValue: 1.0, minValue: 0.0, maxValue: 1.0 },
      { name: 'release', defaultValue: 0.1, minValue: 0.001, maxValue: 5.0 },
      { name: 'freeze', defaultValue: 0.0, minValue: 0.0, maxValue: 1.0 },
      { name: 'freezeLfoRate', defaultValue: 0.0, minValue: 0.0, maxValue: 20.0 },
      { name: 'freezeLfoDepth', defaultValue: 0.0, minValue: 0.0, maxValue: 1.0 },
      { name: 'freezeEnvDepth', defaultValue: 0.0, minValue: 0.0, maxValue: 1.0 },
      { name: 'timeStretchEnvDepth', defaultValue: 0.0, minValue: -1.0, maxValue: 1.0 },
      { name: 'grainEnvDepth', defaultValue: 0.0, minValue: 0.0, maxValue: 1.0 },
      { name: 'grainLfoRate', defaultValue: 0.0, minValue: 0.0, maxValue: 20.0 },
      { name: 'grainLfoDepth', defaultValue: 0.0, minValue: 0.0, maxValue: 1.0 },
      { name: 'grainJitter', defaultValue: 0.0, minValue: 0.0, maxValue: 1.0 },
      { name: 'grainPitchEnvDepth', defaultValue: 0.0, minValue: 0.0, maxValue: 1.0 },
      { name: 'grainPitchQuantize', defaultValue: 0.0, minValue: 0.0, maxValue: 12.0 },
      { name: 'grainPanSpread', defaultValue: 0.0, minValue: 0.0, maxValue: 1.0 },
      { name: 'granularPitchShift', defaultValue: 0.0, minValue: -24.0, maxValue: 24.0 },
      { name: 'tranceGate', defaultValue: 0.0, minValue: 0.0, maxValue: 1.0 },
      { name: 'bitcrush', defaultValue: 0.0, minValue: 0.0, maxValue: 1.0 },
      { name: 'spectralComp', defaultValue: 0.0, minValue: 0.0, maxValue: 1.0 },
      { name: 'downsample', defaultValue: 1.0, minValue: 1.0, maxValue: 32.0 },
      { name: 'windowShape', defaultValue: 0.0, minValue: 0.0, maxValue: 3.0 },
      { name: 'subHarmonics', defaultValue: 0.0, minValue: 0.0, maxValue: 1.0 }
    ];
  }

  // Sub Harmonics State
  private subState = {
    // Zero crossing and toggle state per channel
    lastSign: [0, 0],
    subToggle: [1, 1],
    // Low pass filter state for smoothing the sub octave square wave
    lp1: [0, 0],
    lp2: [0, 0]
  };

  constructor() {
    super();
    this.port.onmessage = this.handleMessage.bind(this);
    // @ts-ignore
    if (typeof globalThis.sampleRate === 'number' && Number.isFinite(globalThis.sampleRate)) {
      this.sampleRate = globalThis.sampleRate;
    }

    this.expressiveProcessor = new ExpressiveVoiceProcessor({
      sampleRate: this.sampleRate
    });
  }

  async handleMessage(event: MessageEvent) {
    const { type, data } = event.data;

    switch (type) {
      case 'INIT_WASM':
        try {
          const { inputBuffer, outputBuffer, wasmBinary, baseUrl } = event.data;

          this.inputRingBuffer = new RingBuffer(inputBuffer);
          this.outputRingBuffer = new RingBuffer(outputBuffer);

          if (!wasmBinary) {
            throw new Error("WASM binary not provided in INIT_WASM message");
          }

          const wasmPath = `${baseUrl || '/'}rubberband.wasm`;
          // Instantiate WASM module with the provided binary
          // @ts-ignore
          const module = await createRubberBandModule({
            wasmBinary: wasmBinary,
            locateFile: (path: string) => {
              if (path.endsWith('.wasm')) return wasmPath;
              return path;
            }
          });

          const safeSampleRate = (Number.isFinite(this.sampleRate) && this.sampleRate > 0)
            ? Math.floor(this.sampleRate)
            : 44100;

          // Options: RealTime (1) | Finer (32) | FormantPreserved (1048576) = 1048609
          const options = 1 | 32 | 1048576;

          console.log(`[RubberBandProcessor] Initializing with: Rate=${safeSampleRate}, Ch=1, Opts=${options}`);

          this.rubberBand = new module.RubberBandStretcher(
            safeSampleRate,
            1, // Mono
            options,
            1.0, // Initial Time Ratio
            1.0  // Initial Pitch Scale
          );

          this.rubberBand.module = module;
          this.initialized = true;
          this.port.postMessage({ type: 'READY' });
        } catch (e) {
          console.error("RubberBand WASM Failed:", e);
          this.port.postMessage({ type: 'ERROR', error: String(e) });
        }
        break;

      case 'loadBuffer':
        if (data && data.buffer) {
          this.fullSampleBuffer = new Float32Array(data.buffer);
        }
        break;

      case 'setCustomWindowShape':
        if (data.shape && data.shape.length > 0) {
          this.customWindowShape = new Float32Array(data.shape);
        } else {
          this.customWindowShape = null;
        }
        break;

      case 'setPhonemeData':
        if (data && data.sharedBuffer) {
          this.phonemeData = new Float32Array(data.sharedBuffer);
          this.phonemeRatios = data.ratios || null;
        }
        break;
      case 'noteOn':
        if (!this.initialized || !this.fullSampleBuffer || !data) return;
        this.rubberBand.reset();

        // Store base pitch for combination with parameters
        this.basePitch = data.pitch || 1.0;
        this.rubberBand.setPitchScale(this.basePitch);
        this.rubberBand.setTimeRatio(1.0);
        this.expressiveProcessor.reset();
        this.expressiveProcessor.noteOn();

        const startSample = Math.max(0, Math.floor(data.startSample || 0));
        const endSample = data.endSample
          ? Math.min(this.fullSampleBuffer.length, Math.floor(data.endSample))
          : this.fullSampleBuffer.length;

        if (startSample >= endSample) return;

        this.isReverse = !!data.reverse;

        // Initialize streaming state
        this.startSamplePtr = startSample;
        this.endSamplePtr = endSample;

        if (this.isReverse) {
          this.currentSamplePtr = endSample - 1;
        } else {
          this.currentSamplePtr = startSample;
        }

        this.isPlaying = true;
        break;

      case 'noteOff':
        const targetTime = data?.time;
        this.expressiveProcessor.noteOff(targetTime);
        break;

      case 'setStretchProfile':
        // Update RubberBand quality options (requires reset)
        if (data && typeof data.profile === 'string') {
          if (this.rubberBand) {
             const timeRatio = this.rubberBand.getTimeRatio();
             const pitchScale = this.rubberBand.getPitchScale();

             let options = 1 | 32 | 1048576; // Default to vocal

             if (data.profile === 'harmonic') {
                 options = 1 | 32 | 256 | 0x02000000; // OptionProcessRealTime | OptionEngineFiner | OptionTransientsMixed | OptionPitchHighQuality
             } else if (data.profile === 'fast') {
                 options = 1; // OptionProcessRealTime | OptionEngineFaster
             } else {
                 options = 1 | 32 | 256 | 1048576; // OptionProcessRealTime | OptionEngineFiner | OptionTransientsMixed | OptionFormantPreserved
             }

             // Free old buffers if they exist
             if (this.inputHeapPtr) this.rubberBand.module._free(this.inputHeapPtr);
             if (this.outputHeapPtr) this.rubberBand.module._free(this.outputHeapPtr);
             this.inputHeapPtr = 0;
             this.outputHeapPtr = 0;
             this.heapSizeFrames = 0;

             // Recreate Stretcher
             this.rubberBand = new this.rubberBand.module.RubberBandStretcher(
               this.sampleRate,
               1, // Mono
               options,
               1.0, // Initial Time Ratio
               1.0  // Initial Pitch Scale
             );



             this.rubberBand.setTimeRatio(timeRatio);
             this.rubberBand.setPitchScale(pitchScale);
          }
        }
        break;

      case 'setAutoFollow':
        // Enable/disable auto pitch following from sequencer
        if (data && typeof data.enabled === 'boolean') {
          // this.autoFollowEnabled = data.enabled;
        }
        break;

      case 'setCustomGrainEnvelope':
        if (data && Array.isArray(data.shape)) {
          this.customGrainEnvelope = data.shape;
        } else {
          this.customGrainEnvelope = null;
        }
        break;
    }
  }

  /**
   * Determine the stretch ratio for the current sample position based on phoneme data.
   */
  /**
   * Determine the phoneme parameters for the current sample position.
   * Returns [stretchRatio, volume, pitchBend, vibDepth, vibRate]
   */
  private getPhonemeDataAtSample(currentSample: number): [number, number, number, number, number, number, number, number] {
    if (!this.phonemeData || !this.phonemeRatios) return [1.0, 1.0, 0.0, -1.0, -1.0, -1.0, -1.0, 0.0];

    const count = this.phonemeData[0];
    // Phoneme data stride is 10 floats: start, end, isVowel, stretch(unused in buffer), volume, pitchBend, vibDepth, vibRate, grainJitter, grainSize
    for (let i = 0; i < count; i++) {
      const baseIndex = 1 + i * 10;
      const start = this.phonemeData[baseIndex];
      const end = this.phonemeData[baseIndex + 1];

      if (currentSample >= start && currentSample < end) {
        const ratio = this.phonemeRatios[i] || 1.0;
        const isVowel = this.phonemeData[baseIndex + 2] !== undefined ? this.phonemeData[baseIndex + 2] : 0.0;
        const volume = this.phonemeData[baseIndex + 4] !== undefined ? this.phonemeData[baseIndex + 4] : 1.0;
        const pitchBend = this.phonemeData[baseIndex + 5] !== undefined ? this.phonemeData[baseIndex + 5] : 0.0;
        const vibDepth = this.phonemeData[baseIndex + 6] !== undefined ? this.phonemeData[baseIndex + 6] : -1.0;
        const vibRate = this.phonemeData[baseIndex + 7] !== undefined ? this.phonemeData[baseIndex + 7] : -1.0;
        const grainJitter = this.phonemeData[baseIndex + 8] !== undefined ? this.phonemeData[baseIndex + 8] : -1.0;
        const grainSize = this.phonemeData[baseIndex + 9] !== undefined ? this.phonemeData[baseIndex + 9] : -1.0;
        return [ratio, volume, pitchBend, vibDepth, vibRate, grainJitter, grainSize, isVowel];
      }
    }
    return [1.0, 1.0, 0.0, -1.0, -1.0, -1.0, -1.0, 0.0];
  }

  process(_inputs: Float32Array[][], outputs: Float32Array[][], parameters: Record<string, Float32Array>): boolean {
    const outputChannel = outputs[0][0];
    const blockFrames = outputChannel?.length ?? 128;
    const endPerf = this.perf.beginProcess(blockFrames);
    try {
    outputChannel.fill(0);

    if (!this.initialized || !this.rubberBand || !this.outputRingBuffer) {
      return true;
    }

    // We need to pass the block's start time to ExpressiveVoiceProcessor for accurate timing.
    // In AudioWorklets, the current time is `globalThis.currentTime`.
    // @ts-ignore
    const currentTime = typeof globalThis.currentTime === 'number' ? globalThis.currentTime : 0;
    this.expressiveProcessor.setCurrentTime(currentTime);

    const envelopeValue = this.expressiveProcessor.getCurrentEnvelopeValue();

    const pitchEnvelopeValue = this.expressiveProcessor.getCurrentPitchEnvelopeValue();


    const pitch = parameters.pitchScale[0];
    const defaultTimeRatio = parameters.timeRatio[0];
    const vibDepth = parameters.vibratoDepth[0];
    const vibRate = parameters.vibratoRate[0];
    const tremDepth = parameters.tremoloDepth[0];
    const tremRate = parameters.tremoloRate ? parameters.tremoloRate[0] : 0;
    const gateDepth = parameters.gateDepth ? parameters.gateDepth[0] : 0;
    const gateRate = parameters.gateRate ? parameters.gateRate[0] : 4.0;
    const bitcrushAmount = parameters.bitcrush ? parameters.bitcrush[0] : 0.0;
    const spectralComp = parameters.spectralComp ? parameters.spectralComp[0] : 0.0;
    const subHarmonicsAmount = parameters.subHarmonics ? parameters.subHarmonics[0] : 0.0;
    const downsampleFactor = parameters.downsample ? parameters.downsample[0] : 1.0;
    const breath = parameters.breathIntensity[0];

    const pitchAttack = parameters.pitchAttack ? parameters.pitchAttack[0] : 0.0;
    const pitchDecay = parameters.pitchDecay ? parameters.pitchDecay[0] : 0.0;
    const pitchAmount = parameters.pitchAmount ? parameters.pitchAmount[0] : 0.0;
    const attack = parameters.attack ? parameters.attack[0] : 0.05;
    const decay = parameters.decay ? parameters.decay[0] : 0.1;
    const sustain = parameters.sustain ? parameters.sustain[0] : 1.0;
    const release = parameters.release ? parameters.release[0] : 0.1;

    let currentVibDepth = vibDepth;
    let currentVibRate = vibRate;
    if (this.isPlaying && this.fullSampleBuffer && this.phonemeData && this.phonemeRatios) {
        const [_, _vol, _pBend, pVibDepth, pVibRate, _gJit, _gSize, _isVow] = this.getPhonemeDataAtSample(this.currentSamplePtr);
        if (pVibDepth !== -1.0) currentVibDepth = pVibDepth;
        if (pVibRate !== -1.0) currentVibRate = pVibRate;
    }

    this.expressiveProcessor.updateConfig({
      vibrato: { depth: currentVibDepth, rate: currentVibRate, enabled: currentVibDepth > 0 },
      tremolo: { depth: tremDepth, rate: tremRate, enabled: tremDepth > 0 },
      gate: { depth: gateDepth, rate: gateRate, enabled: gateDepth > 0 },
      breath: { amount: breath, enabled: breath > 0, filterCutoff: 2000 },

      envelope: { attack, decay, sustain, release },
      pitchEnvelope: { attack: pitchAttack, decay: pitchDecay, amount: pitchAmount }

    });

    // Combine note pitch with parameter modulation
    let finalPitch = this.isPlaying ? this.basePitch * pitch : pitch;


    // Apply Pitch Envelope
    if (pitchAmount !== 0.0 && pitchEnvelopeValue > 0.0) {
      // Amount is in semitones. Pitch envelope value is 0.0 to 1.0.
      const pitchEnvSemitones = pitchAmount * pitchEnvelopeValue;
      const pitchEnvRatio = Math.pow(2.0, pitchEnvSemitones / 12.0);
      finalPitch *= pitchEnvRatio;
    }

    // Granular Pitch Shift & Envelope
    let granularPitchShift = parameters.granularPitchShift ? parameters.granularPitchShift[0] : 0.0;

    // Apply Granular Pitch Envelope (maps envelope 0-1 to shift amount, similar to main pitch env)
    const grainPitchEnvDepth = parameters.grainPitchEnvDepth ? parameters.grainPitchEnvDepth[0] : 0.0;
    if (grainPitchEnvDepth !== 0.0 && pitchEnvelopeValue > 0.0) {
        const maxEnvShift = 24.0;
        granularPitchShift += (maxEnvShift * grainPitchEnvDepth * pitchEnvelopeValue);
    }

    if (granularPitchShift !== 0.0) {
      const pitchShiftRatio = Math.pow(2.0, granularPitchShift / 12.0);
      finalPitch *= pitchShiftRatio;
    }

    // Apply Phoneme Pitch Bend (if we're streaming from a buffer and have it calculated)
    if (this.isPlaying && this.fullSampleBuffer && this.phonemeData && this.phonemeRatios) {
        const [_, _vol, pBend, _vDepth, _vRate, _gJit, _gSize, _isVow] = this.getPhonemeDataAtSample(this.currentSamplePtr);
        if (pBend !== 0.0) {
            const pitchBendRatio = Math.pow(2.0, pBend / 1200.0);
            finalPitch *= pitchBendRatio;
        }
    }

    // Granular Pitch Quantization: snap pitch to intervals when active
    const grainPitchQuantize = parameters.grainPitchQuantize ? parameters.grainPitchQuantize[0] : 0.0;
    if (grainPitchQuantize > 0.0 && finalPitch > 0.0) {
      const semitones = 12.0 * Math.log2(finalPitch);
      const quantizedSemitones = Math.round(semitones / grainPitchQuantize) * grainPitchQuantize;
      finalPitch = Math.pow(2.0, quantizedSemitones / 12.0);
    }

    this.rubberBand.setPitchScale(finalPitch);

    try {
      // STREAMING INPUT LOGIC
      // If playing a note, stream from fullSampleBuffer with phoneme-aware time stretching
      if (this.isPlaying && this.fullSampleBuffer) {
        // Calculate dynamic time ratio based on phoneme data
        let ratio = defaultTimeRatio;
        let phonemeVolume = 1.0;
        let phonemePitchBendCents = 0.0;
        if (this.phonemeData && this.phonemeRatios) {
          const [pRatio, pVol, pBend, _vDepth, _vRate, _gJit, _gSize, _isVow] = this.getPhonemeDataAtSample(this.currentSamplePtr);
          ratio = pRatio;
          phonemeVolume = pVol;
          phonemePitchBendCents = pBend;
        }

        // Apply Time-Stretch Envelope modulation
        const timeStretchEnvDepth = parameters.timeStretchEnvDepth ? parameters.timeStretchEnvDepth[0] : 0.0;
        const timeModulation = timeStretchEnvDepth * envelopeValue * 3.0; // scale factor
        ratio = Math.max(0.1, Math.min(4.0, ratio + timeModulation));

        this.rubberBand.setTimeRatio(ratio);

        const samplesRequired = this.rubberBand.getSamplesRequired();

        const freezeBase = parameters.freeze ? parameters.freeze[0] : 0.0;
        const freezeLfoRate = parameters.freezeLfoRate ? parameters.freezeLfoRate[0] : 0.0;
        const freezeLfoDepth = parameters.freezeLfoDepth ? parameters.freezeLfoDepth[0] : 0.0;
        const freezeEnvDepth = parameters.freezeEnvDepth ? parameters.freezeEnvDepth[0] : 0.0;
        const grainEnvDepth = parameters.grainEnvDepth ? parameters.grainEnvDepth[0] : 0.0;
        const windowShape = parameters.windowShape ? parameters.windowShape[0] : 0.0;
        const grainLfoRate = parameters.grainLfoRate ? parameters.grainLfoRate[0] : 0.0;
        const grainLfoDepth = parameters.grainLfoDepth ? parameters.grainLfoDepth[0] : 0.0;

        // Advance LFO phase (we can do this per block/process call rather than per sample since block is 128 samples (~2.9ms at 44.1kHz),
        // which is fast enough for low-frequency LFOs up to 20Hz. We'll add the increment based on the block size).
        // Wait, the plan explicitly said "Update this.freezeLfoPhase by adding 2 * Math.PI * freezeLfoRate / sampleRate for each sample processed in the block".
        // Let's do it per sample below when processing if it's frozen, OR just compute it once per block if we just need a single freeze decision for the block.
        // Actually, the freeze decision is for the *entire block* because we feed `samplesRequired` to RubberBand.
        // So we just advance it once by block size (128 samples).
        const sRate = typeof globalThis.sampleRate === 'number' ? globalThis.sampleRate : 44100;
        const framesInBlock = 128; // standard Web Audio block size
        this.freezeLfoPhase += (2 * Math.PI * freezeLfoRate * framesInBlock) / sRate;
        if (this.freezeLfoPhase > 2 * Math.PI) {
            this.freezeLfoPhase -= 2 * Math.PI;
        }

        this.grainLfoPhase += (2 * Math.PI * grainLfoRate * framesInBlock) / sRate;
        if (this.grainLfoPhase > 2 * Math.PI) {
            this.grainLfoPhase -= 2 * Math.PI;
        }

        const lfoValue = Math.sin(this.freezeLfoPhase);
        // Map sine from [-1, 1] to [0, 1] for unipolar modulation, or keep it bipolar?
        // Let's use bipolar modulation: freezeBase + freezeLfoDepth * sin
        // Add envelope follower modulation
        let freezeAmt = freezeBase + (freezeLfoDepth * lfoValue) + (freezeEnvDepth * envelopeValue);
        freezeAmt = Math.max(0.0, Math.min(1.0, freezeAmt));

        const isFrozen = freezeAmt > 0.5;

        if (isFrozen) {
          if (!this.wasFrozen) {
            this.grainWrapPending = true;
          }
          this.wasFrozen = true;

          // FREEZE STREAMING (Spectral Granulator)
          // Don't advance the pointer, just loop a small grain
          if (samplesRequired > 0) {
            const samplesToFeed = samplesRequired;
            this.ensureHeapSize(samplesToFeed);

            const heap = this.rubberBand.module.HEAPF32;
            const ptr = this.inputHeapPtr >> 2;
            const buf = this.fullSampleBuffer;

            // Define grain size: ~100ms
            // Using globalThis.sampleRate safely, fallback to 44100
            // @ts-ignore
            const sRate = typeof globalThis.sampleRate === 'number' ? globalThis.sampleRate : 44100;
            let baseGrainSize = Math.floor(sRate * 0.1);

            let grainJitter = parameters.grainJitter ? parameters.grainJitter[0] : 0.0;

            // Check for per-phoneme overrides
            if (this.phonemeData && this.phonemeRatios) {
                const [_, _pVol, _pBend, _vDepth, _vRate, pGrainJitter, pGrainSize, _isVow] = this.getPhonemeDataAtSample(this.currentSamplePtr);
                if (pGrainJitter !== -1.0) {
                    grainJitter = pGrainJitter;
                }
                if (pGrainSize !== -1.0) {
                    // Overwrite base grain size with custom size (in ms converted to samples)
                    baseGrainSize = Math.floor(sRate * (pGrainSize / 1000));
                }
            }

            const grainLfoValue = Math.sin(this.grainLfoPhase);
            // Apply unipolar LFO modulation to grain size (reduces size)
            const lfoMod = 1.0 - (grainLfoDepth * ((grainLfoValue + 1) * 0.5));

            // Modulate grain size with envelope: louder = smaller grains for more texture
            const maxJitterSamples = Math.floor(0.05 * sRate * grainJitter);

            const initGrain = (g: any) => {
                const grainSizeSamplesActive = Math.max(100, Math.floor(baseGrainSize * lfoMod * (1.0 - grainEnvDepth * envelopeValue)));
                const jitterOffsetActive = maxJitterSamples > 0 ? Math.floor((Math.random() * 2 - 1) * maxJitterSamples) : 0;
                const grainCenterActive = this.currentSamplePtr + jitterOffsetActive;
                g.start = Math.max(0, Math.min(buf.length - grainSizeSamplesActive, grainCenterActive - Math.floor(grainSizeSamplesActive / 2)));
                g.size = Math.min(buf.length, g.start + grainSizeSamplesActive) - g.start;
                g.phase = 0;
                g.active = g.size > 0;
            };

            // Ensure at least one grain is active
            if (!this.grains[0].active && !this.grains[1].active) {
                initGrain(this.grains[0]);
            }

            const hasActiveGrain = this.grains[0].active || this.grains[1].active;

            if (hasActiveGrain) {
              for (let i = 0; i < samplesToFeed; i++) {
                let sampleVal = 0;
                for (let gIdx = 0; gIdx < 2; gIdx++) {
                    const g = this.grains[gIdx];
                    if (g.active) {
                        const phase = g.phase / (g.size - 1);
                        let windowVal = 1.0;

                        if (this.customWindowShape && this.customWindowShape.length > 0) {
                            const index = phase * (this.customWindowShape.length - 1);
                            const lower = Math.floor(index);
                            const upper = Math.ceil(index);
                            const weight = index - lower;
                            windowVal = this.customWindowShape[lower] * (1 - weight) + this.customWindowShape[upper] * weight;
                        } else if (this.customGrainEnvelope && this.customGrainEnvelope.length > 0) {
                            const idx = phase * (this.customGrainEnvelope.length - 1);
                            const lowerIdx = Math.floor(idx);
                            const upperIdx = Math.ceil(idx);
                            const fraction = idx - lowerIdx;

                            const lowerVal = this.customGrainEnvelope[lowerIdx];
                            const upperVal = this.customGrainEnvelope[upperIdx];

                            windowVal = lowerVal + (upperVal - lowerVal) * fraction;
                        } else {
                            // 0: Hann, 1: Hamming, 2: Blackman, 3: Rectangular (None)
                            if (windowShape < 0.5) {
                                // Hann
                                windowVal = 0.5 * (1 - Math.cos(2 * Math.PI * phase));
                            } else if (windowShape < 1.5) {
                                // Hamming
                                windowVal = 0.54 - 0.46 * Math.cos(2 * Math.PI * phase);
                            } else if (windowShape < 2.5) {
                                // Blackman
                                windowVal = 0.42 - 0.5 * Math.cos(2 * Math.PI * phase) + 0.08 * Math.cos(4 * Math.PI * phase);
                            } else {
                                // Rectangular / None
                                windowVal = 1.0;
                            }
                        }

                        sampleVal += buf[g.start + g.phase] * windowVal;
                        g.phase++;

                        // Check if we should start the other grain (50% overlap)
                        const otherIdx = gIdx === 0 ? 1 : 0;
                        const otherG = this.grains[otherIdx];
                        if (g.phase === Math.floor(g.size / 2) && !otherG.active) {
                            initGrain(otherG);
                        }

                        if (g.phase >= g.size) {
                            g.active = false;
                            if (gIdx === 0) {
                                // Only trigger grain wrap panning when the primary grain finishes
                                // to avoid double triggers that flutter the stereo field too much
                                this.grainWrapPending = true;
                            }
                        }
                    }
                }
                heap[ptr + i] = sampleVal;
              }
              this.rubberBand.process(this.inputHeapPtr, samplesToFeed, false);
            } else {
              // Fallback if grain is empty
               this.rubberBand.process(this.inputHeapPtr, 0, false);
            }
          }
        } else {
          this.grains[0].active = false;
          this.grains[1].active = false; // Reset phase when unfreezing
          if (this.wasFrozen) {
            this.grainWrapPending = false;
            this.wasFrozen = false;
            // Restore dual-mono on unfreeze
            this.grainPanL.fill(Math.SQRT1_2);
            this.grainPanR.fill(Math.SQRT1_2);
            // Clear SVF states to avoid bleed from panned grains
            this.scLow.fill(0);
            this.scHigh.fill(0);
          }

          if (this.isReverse) {
            // REVERSE STREAMING
            const samplesRemaining = this.currentSamplePtr - this.startSamplePtr + 1;

            if (samplesRemaining > 0 && samplesRequired > 0) {
              const samplesToFeed = Math.min(samplesRemaining, samplesRequired);
              this.ensureHeapSize(samplesToFeed);

              // Manually copy in reverse order
              const heap = this.rubberBand.module.HEAPF32;
              const ptr = this.inputHeapPtr >> 2;
              const buf = this.fullSampleBuffer;
              let readPtr = this.currentSamplePtr;

              for (let i = 0; i < samplesToFeed; i++) {
                heap[ptr + i] = buf[readPtr--];
              }

              this.rubberBand.process(this.inputHeapPtr, samplesToFeed, false);
              this.currentSamplePtr = readPtr;
            }
          } else {
            // FORWARD STREAMING
            const samplesRemaining = this.endSamplePtr - this.currentSamplePtr;

            if (samplesRemaining > 0 && samplesRequired > 0) {
              const samplesToFeed = Math.min(samplesRemaining, samplesRequired);
              this.ensureHeapSize(samplesToFeed);

              // Copy directly to WASM heap
              const slice = this.fullSampleBuffer.subarray(
                this.currentSamplePtr,
                this.currentSamplePtr + samplesToFeed
              );
              this.rubberBand.module.HEAPF32.set(slice, this.inputHeapPtr >> 2);

              this.rubberBand.process(this.inputHeapPtr, samplesToFeed, false);
              this.currentSamplePtr += samplesToFeed;
            }
          }
        }
      }
      // Fallback: Check RingBuffer input (for real-time mic usage if supported later)
      else if (this.inputRingBuffer && this.inputRingBuffer.availableRead() > 0) {
        const required = this.rubberBand.getSamplesRequired();
        const available = this.inputRingBuffer.availableRead();
        if (available >= required && required > 0) {
          this.ensureHeapSize(required);
          const inputView = this.rubberBand.module.HEAPF32.subarray(
            this.inputHeapPtr >> 2, (this.inputHeapPtr >> 2) + required
          );
          this.inputRingBuffer.pull(inputView);
          this.rubberBand.process(this.inputHeapPtr, required, false);
        }
      }

      // --- OUTPUT RETRIEVAL LOGIC ---
      const availOutput = this.rubberBand.available();
      if (availOutput > 0) {
        const framesToRead = Math.min(availOutput, outputChannel.length);
        this.ensureHeapSize(framesToRead);

        const retrieved = this.rubberBand.retrieve(this.outputHeapPtr, framesToRead);
        const outputView = this.rubberBand.module.HEAPF32.subarray(
          this.outputHeapPtr >> 2,
          (this.outputHeapPtr >> 2) + retrieved
        );

        outputChannel.set(outputView);
        this.expressiveProcessor.process(outputChannel, outputChannel);

        // Apply phoneme volume
        if (this.isPlaying && this.fullSampleBuffer && this.phonemeData && this.phonemeRatios) {
            const [_, pVol, _pBend, _vDepth, _vRate, _gJit, _gSize, _isVow] = this.getPhonemeDataAtSample(this.currentSamplePtr);
            if (pVol !== 1.0) {
                for (let i = 0; i < outputChannel.length; i++) {
                    outputChannel[i] *= pVol;
                }
            }
        }

        // Apply Rhythmic Gating (Trance Gate)
      const gateDepth = parameters.gateDepth ? parameters.gateDepth[0] : 0.0;
      const gateRate = parameters.gateRate ? parameters.gateRate[0] : 0.0;

      if (gateDepth > 0 && gateRate > 0) {
        const sampleRate = (globalThis as any).sampleRate ?? 44100;
        const phaseIncrement = (2 * Math.PI * gateRate) / sampleRate;

        for (let i = 0; i < outputChannel.length; i++) {
          this.gatePhase += phaseIncrement;
          if (this.gatePhase > 2 * Math.PI) {
            this.gatePhase -= 2 * Math.PI;
          }

          const targetGate = Math.sin(this.gatePhase) > 0 ? 1.0 : 0.0;

          // ~4–6 ms one-pole smoothing at 44.1/48 kHz — tight but click-free
          this.currentGateLfo = this.currentGateLfo * 0.92 + targetGate * 0.08;

          const gateMultiplier = 1.0 - (gateDepth * (1.0 - this.currentGateLfo));
          outputChannel[i] *= gateMultiplier;
        }
      }

  const grainPanSpread = parameters.grainPanSpread ? parameters.grainPanSpread[0] : 0.0;
  const spectralCompression = parameters.spectralCompression
    ? parameters.spectralCompression[0]
    : 0.0;
  // spectralComp already read earlier on main
  if (grainPanSpread > 0 && this.grainWrapPending) {
    this.grainWrapPending = false;
    const [_, __, ___, ____, _____, ______, _______, isVowel] = this.getPhonemeDataAtSample(this.currentSamplePtr);
    const finalPanSpread = isVowel > 0 ? grainPanSpread : grainPanSpread * 0.3;

    for (let b = 0; b < 3; b++) {
      const spreadMod = b === 0 ? 0.4 : b === 1 ? 0.8 : 1.2;
      const pan = (Math.random() * 2 - 1) * Math.min(1.0, finalPanSpread * spreadMod);
      const angle = ((pan + 1.0) * 0.5) * Math.PI / 2;
      this.grainPanL[b] = Math.cos(angle);
      this.grainPanR[b] = Math.sin(angle);
    }
  } else if (grainPanSpread === 0) {
    this.grainPanL.fill(Math.SQRT1_2);
    this.grainPanR.fill(Math.SQRT1_2);
  }
  const outL = outputs[0][0];
  const outR = outputs[0][1];
  const hasStereo = !!(outL && outR);
  const needSplit =
    spectralComp > 0 ||
    spectralCompression > 0 ||
    (grainPanSpread > 0 && hasStereo);
  if (needSplit) {
    const fs = this.sampleRate || (globalThis as { sampleRate?: number }).sampleRate || 44100;
    const f1_c = 2 * Math.sin(Math.PI * 300 / fs);
    const f2_c = 2 * Math.sin(Math.PI * 3000 / fs);
    const q = 0.5;
    const attackCoef = Math.exp(-1.0 / (fs * (2.0 / 1000.0)));
    const releaseCoef = Math.exp(-1.0 / (fs * (50.0 / 1000.0)));
    const maxGR = 12.0 * spectralComp;
    const threshold = 0.1;
    const ratio = 1.0 + 3.0 * spectralComp;
    const channel = 0;
    for (let i = 0; i < outL.length; i++) {
      const x = outL[i];
      this.scState.lp1[channel] += f1_c * this.scState.bp1[channel];
      const hp1 = x - this.scState.lp1[channel] - q * this.scState.bp1[channel];
      this.scState.bp1[channel] += f1_c * hp1;
      let low = this.scState.lp1[channel];
      const rest = hp1;
      this.scState.lp2[channel] += f2_c * this.scState.bp2[channel];
      let high = rest - this.scState.lp2[channel] - q * this.scState.bp2[channel];
      this.scState.bp2[channel] += f2_c * high;
      let mid = this.scState.lp2[channel];
      const bands = [low, mid, high];
      if (spectralComp > 0) {
        for (let b = 0; b < 3; b++) {
          const absIn = Math.abs(bands[b]);
          const env = this.scState.env;
          if (absIn > env[b]) {
            env[b] = attackCoef * env[b] + (1 - attackCoef) * absIn;
          } else {
            env[b] = releaseCoef * env[b] + (1 - releaseCoef) * absIn;
          }
          let gain = 1.0;
          if (env[b] > threshold) {
            const over = 20 * Math.log10(env[b]) - 20 * Math.log10(threshold);
            const grDb = Math.min(over * (1.0 - 1.0 / ratio), maxGR);
            gain = Math.pow(10, -grDb / 20);
          }
          bands[b] *= gain;
        }
      }
      low = bands[0];
      mid = bands[1];
      high = bands[2];
      if (spectralCompression > 0) {
        const attackConst = 1 - Math.exp(-1.0 / (fs * 0.005));
        const releaseConst = 1 - Math.exp(-1.0 / (fs * 0.070));
        const absLow = Math.abs(low);
        const absMid = Math.abs(mid);
        const absHigh = Math.abs(high);
        this.scEnvLow[channel] += (absLow > this.scEnvLow[channel] ? attackConst : releaseConst) * (absLow - this.scEnvLow[channel]);
        this.scEnvMid[channel] += (absMid > this.scEnvMid[channel] ? attackConst : releaseConst) * (absMid - this.scEnvMid[channel]);
        this.scEnvHigh[channel] += (absHigh > this.scEnvHigh[channel] ? attackConst : releaseConst) * (absHigh - this.scEnvHigh[channel]);
        const targetRMS = 0.15;
        const gainLow = Math.max(0.1, Math.min(4.0, 1.0 + spectralCompression * (targetRMS / (this.scEnvLow[channel] + 0.001) - 1.0) * 0.5));
        const gainMid = Math.max(0.1, Math.min(3.0, 1.0 + spectralCompression * (targetRMS / (this.scEnvMid[channel] + 0.001) - 1.0) * 0.7));
        const gainHigh = Math.max(0.1, Math.min(4.0, 1.0 + spectralCompression * (targetRMS / (this.scEnvHigh[channel] + 0.001) - 1.0) * 0.6));
        low = low * (1.0 - spectralCompression) + low * gainLow * spectralCompression;
        mid = mid * (1.0 - spectralCompression) + mid * gainMid * spectralCompression;
        high = high * (1.0 - spectralCompression) + high * gainHigh * spectralCompression;
      }
      if (hasStereo) {
        outL[i] = low * this.grainPanL[0] + mid * this.grainPanL[1] + high * this.grainPanL[2];
        outR[i] = low * this.grainPanR[0] + mid * this.grainPanR[1] + high * this.grainPanR[2];
      } else {
        outL[i] = low + mid + high;
      }
    }
  } else if (hasStereo) {
    outR.set(outL);
  }
        
      if (spectralComp > 0) {
        const f1 = 300;
        const f2 = 3000;
        const fs = (globalThis as any).sampleRate ?? 44100;

        // Chamberlin SVF coefficients
        const f1_c = 2 * Math.sin(Math.PI * f1 / fs);
        const f2_c = 2 * Math.sin(Math.PI * f2 / fs);
        const q = 0.5; // Butterworth-ish

        // Envelope constants
        const attackMs = 2.0;
        const releaseMs = 50.0;
        const attackCoef = Math.exp(-1.0 / (fs * (attackMs / 1000.0)));
        const releaseCoef = Math.exp(-1.0 / (fs * (releaseMs / 1000.0)));

        // Max gain reduction in dB
        const maxGR = 12.0 * spectralComp;
        const threshold = 0.1; // -20 dB
        const ratio = 1.0 + (3.0 * spectralComp); // up to 4:1

        for (let channel = 0; channel < outputs[0].length; channel++) {
          const outCh = outputs[0][channel];
          if (!outCh) continue;
          if (channel > 1) continue; // stereo only for now

          for (let i = 0; i < outCh.length; i++) {
            const x = outCh[i];

            // Crossover 1 (Low / Rest)
            this.scState.lp1[channel] += f1_c * this.scState.bp1[channel];
            const hp1 = x - this.scState.lp1[channel] - q * this.scState.bp1[channel];
            this.scState.bp1[channel] += f1_c * hp1;
            const low = this.scState.lp1[channel];
            const rest = hp1;

            // Crossover 2 (Mid / High)
            this.scState.lp2[channel] += f2_c * this.scState.bp2[channel];
            const high = rest - this.scState.lp2[channel] - q * this.scState.bp2[channel];
            this.scState.bp2[channel] += f2_c * high;
            const mid = this.scState.lp2[channel];

            const bands = [low, mid, high];
            let outSum = 0;

            for (let b = 0; b < 3; b++) {
              const absIn = Math.abs(bands[b]);

              if (absIn > this.scState.env[b]) {
                this.scState.env[b] = attackCoef * this.scState.env[b] + (1 - attackCoef) * absIn;
              } else {
                this.scState.env[b] = releaseCoef * this.scState.env[b] + (1 - releaseCoef) * absIn;
              }

              let gain = 1.0;
              if (this.scState.env[b] > threshold) {
                const envDb = 20 * Math.log10(this.scState.env[b]);
                const threshDb = 20 * Math.log10(threshold);
                const over = envDb - threshDb;
                let grDb = over * (1.0 - (1.0 / ratio));
                grDb = Math.min(grDb, maxGR);
                gain = Math.pow(10, -grDb / 20);
              }
              outSum += bands[b] * gain;
            }
            outCh[i] = outSum;
          }
        }
      } else if (hasStereo) {
        // If neither effect is active, but we have stereo output, just copy L to R
        outR.set(outL);
      }

      // Generate Sub-Harmonics (Vowels only)
      if (subHarmonicsAmount > 0) {
        // Evaluate vowel state via phoneme stride
        const [_, __, ___, ____, _____, ______, _______, isVowel] = this.getPhonemeDataAtSample(this.currentSamplePtr);

        if (isVowel > 0) {
          const fs = this.sampleRate || (globalThis as { sampleRate?: number }).sampleRate || 44100;
          // Simple 1-pole LPF for the sub-octave square wave, cutoff around 80Hz
          const cutoffFreq = 80;
          const rc = 1.0 / (2.0 * Math.PI * cutoffFreq);
          const dt = 1.0 / fs;
          const alpha = dt / (rc + dt);

          for (let channel = 0; channel < outputs[0].length; channel++) {
            const outCh = outputs[0][channel];
            if (!outCh) continue;
            if (channel > 1) continue; // Stereo only

            for (let i = 0; i < outCh.length; i++) {
              const x = outCh[i];

              // Zero crossing detector to divide frequency by 2
              const currentSign = x >= 0 ? 1 : -1;
              if (currentSign !== this.subState.lastSign[channel]) {
                 if (currentSign === 1) { // Positive edge
                    this.subState.subToggle[channel] = -this.subState.subToggle[channel];
                 }
                 this.subState.lastSign[channel] = currentSign;
              }

              // Raw sub-octave square wave
              const rawSub = this.subState.subToggle[channel] * 0.5; // Scale down a bit initially

              // Apply low-pass filter twice (2-pole approximation) to make it smooth/sine-like
              this.subState.lp1[channel] = this.subState.lp1[channel] + alpha * (rawSub - this.subState.lp1[channel]);
              this.subState.lp2[channel] = this.subState.lp2[channel] + alpha * (this.subState.lp1[channel] - this.subState.lp2[channel]);

              // Apply subtle soft-clipping saturation to the sub-harmonic
              // This adds upper harmonics to help the sub cut through on smaller speakers
              const drive = 2.5;
              const drivenSub = this.subState.lp2[channel] * 4.0 * drive;
              const saturatedSub = drivenSub / (1.0 + Math.abs(drivenSub));

              // Compensate for gain loss and mix with the dry signal
              const finalSub = (saturatedSub / drive) * 4.0;
              outCh[i] = x + (finalSub * subHarmonicsAmount);
            }
          }
        }
      }
        
      // Apply Bitcrush & Downsample
      if (bitcrushAmount > 0 || downsampleFactor > 1.0) {
        for (let channel = 0; channel < outputs[0].length; channel++) {
          const outCh = outputs[0][channel];
          if (!outCh) continue;

          for (let i = 0; i < outCh.length; i++) {
            this.downsamplePhase[channel] += 1.0;
            if (this.downsamplePhase[channel] >= downsampleFactor) {
              this.downsamplePhase[channel] -= downsampleFactor;

              // Bitcrush
              if (bitcrushAmount > 0) {
                  // bitcrushAmount 0.0 -> 16 bits, 1.0 -> 2 bits
                  // Map 0-1 to 16-2 bits linearly
                  const bits = 16 - (bitcrushAmount * 14);
                  const steps = Math.pow(2, bits);
                  this.lastSampleValue[channel] = Math.floor(outCh[i] * steps) / steps;
              } else {
                  this.lastSampleValue[channel] = outCh[i];
              }
            }
            outCh[i] = this.lastSampleValue[channel];
          }
        }
      }
        // Check for completion when no output is available but we're still marked as playing
        if (this.isReverse) {
          if (this.currentSamplePtr < this.startSamplePtr) this.isPlaying = false;
        } else {
          if (this.currentSamplePtr >= this.endSamplePtr) this.isPlaying = false;
        }
      }

    } catch (e) {
      console.error("DSP Error:", e);
    }

    return true;
    } finally {
      endPerf();
    }
  }

  private ensureHeapSize(frames: number) {
    if (frames > this.heapSizeFrames) {
      if (this.inputHeapPtr) this.rubberBand.module._free(this.inputHeapPtr);
      if (this.outputHeapPtr) this.rubberBand.module._free(this.outputHeapPtr);

      this.inputHeapPtr = this.rubberBand.module._malloc(frames * 4);
      this.outputHeapPtr = this.rubberBand.module._malloc(frames * 4);
      this.heapSizeFrames = frames;
    }
  }
}

registerProcessor('RubberBandProcessor', RubberBandProcessor);