/**
 * AISongModal - Import AI-generated songs
 *
 * A production-ready modal dialog for importing songs generated by external AI systems
 * (Claude, Gemini, Jules, Copilot, Grok, etc.)
 */

import React from 'react';
import type { AISongModalProps } from '../types/aiSongModal';
import { useAISongModal } from './ai-song-modal/useAISongModal';
import { useAISongPreviewElements } from './ai-song-modal/useAISongPreviewElements';
import { AISongModalHeader } from './ai-song-modal/AISongModalHeader';
import { AISongModalTabs } from './ai-song-modal/AISongModalTabs';
import { AISongModalFooter, ImportProgressBar } from './ai-song-modal/AISongModalFooter';
import { PasteTabPanel } from './ai-song-modal/PasteTabPanel';
import { TemplateTabPanel } from './ai-song-modal/TemplateTabPanel';
import { PreviewTabPanel } from './ai-song-modal/PreviewTabPanel';

export const AISongModal = React.memo(function AISongModal({
  isOpen,
  onClose,
  onImport,
  onShowToast,
  audioEngine,
}: AISongModalProps): React.ReactElement | null {
  const modal = useAISongModal({ isOpen, onClose, onImport, onShowToast });
  const preview = useAISongPreviewElements(modal.parsedData, modal.trackStats);

  if (!isOpen) return null;

  return (
    <div
      ref={modal.modalRef}
      className="fixed inset-0 bg-black/70 backdrop-blur-sm z-50 flex items-center justify-center p-2 sm:p-4"
    >
      <div
        className="absolute inset-0 z-0"
        onClick={modal.handleClose}
        aria-hidden="true"
      />
      <div
        role="dialog"
        aria-modal="true"
        aria-labelledby="ai-song-modal-title"
        aria-describedby="ai-song-modal-desc"
        tabIndex={-1}
        className="relative z-10 bg-[#0f1115] border border-emerald-500/30 rounded-xl shadow-[0_0_60px_rgba(16,185,129,0.2)] w-full max-w-3xl max-h-[95vh] sm:max-h-[90vh] flex flex-col animate-in fade-in zoom-in-95 duration-200"
        onDragEnter={modal.handleDragEnter}
        onDragLeave={modal.handleDragLeave}
        onDragOver={(e) => e.preventDefault()}
        onDrop={modal.handleDrop}
      >
        <AISongModalHeader
          onClose={modal.handleClose}
          validationState={modal.validationState}
          showCloseConfirm={modal.showCloseConfirm}
          onDismissCloseConfirm={() => modal.setShowCloseConfirm(false)}
          onConfirmClose={modal.confirmClose}
        />

        <AISongModalTabs
          activeTab={modal.activeTab}
          isValid={modal.isValid}
          onTabChange={modal.setActiveTab}
        />

        <div className="flex-1 overflow-auto p-3 sm:p-4">
          {modal.activeTab === 'paste' ? (
            <PasteTabPanel
              jsonInput={modal.jsonInput}
              validationState={modal.validationState}
              hasErrors={modal.hasErrors}
              isValid={modal.isValid}
              parsedData={modal.parsedData}
              isDragging={modal.isDragging}
              droppedFiles={modal.droppedFiles}
              showFixSuccess={modal.showFixSuccess}
              copiedError={modal.copiedError}
              textareaRef={modal.textareaRef}
              fileInputRef={modal.fileInputRef}
              onJsonChange={modal.handleJsonChange}
              onImport={modal.handleImport}
              onFileSelect={modal.handleFileSelect}
              onRemoveFile={modal.removeDroppedFile}
              onLoadExample={modal.loadExample}
              onFixCommonIssues={modal.handleFixCommonIssues}
              onCopyErrorReport={modal.copyErrorReport}
              parsedTracksElements={preview.parsedTracksElements}
              parsedAutomationLanesList={preview.parsedAutomationLanesList}
            />
          ) : modal.activeTab === 'template' ? (
            <TemplateTabPanel onCopyTemplate={modal.copyTemplate} />
          ) : (
            <PreviewTabPanel
              isPreviewLoading={modal.isPreviewLoading}
              parsedData={modal.parsedData}
              trackStats={modal.trackStats}
              patternGrid={modal.patternGrid}
              trackStatisticsRows={preview.trackStatisticsRows}
              parsedAutomationRows={preview.parsedAutomationRows}
              audioEngine={audioEngine}
              onShowToast={onShowToast}
            />
          )}
        </div>

        {modal.isImporting && <ImportProgressBar importStages={modal.importStages} />}

        <AISongModalFooter
          validationState={modal.validationState}
          jsonInput={modal.jsonInput}
          parsedData={modal.parsedData}
          isImporting={modal.isImporting}
          onClose={modal.handleClose}
          onImport={modal.handleImport}
        />
      </div>
    </div>
  );
});

export default AISongModal;
