/**
 * AISongModal - Import AI-generated songs
 * 
 * A modal dialog for importing songs generated by external AI systems
 * (Claude, Gemini, Jules, Copilot, Grok, etc.)
 * 
 * Features:
 * - Paste JSON directly
 * - Drag & drop .json files
 * - Validate before import
 * - Preview song metadata
 * - Real-time validation feedback
 * - Progress bar during import
 * - Example songs (Techno, House, Ambient)
 * - Field-level error reporting
 * - Auto-fix common issues
 */

import React, { useState, useRef, useCallback, useEffect, useMemo } from 'react';
import { 
  AISongImporter, 
  parseAISongJSON, 
  type AISongData, 
  type AIImportResultType,
  type AIImportErrorDetails
} from '../importers/ai-song';
import type { SavedSongData } from '../types';

type TabType = 'paste' | 'template' | 'preview';
type ValidationStage = 'idle' | 'parsing' | 'validating' | 'converting' | 'complete' | 'error';
type ErrorCategory = 'JSON_SYNTAX' | 'SCHEMA_VIOLATION' | 'CONVERSION_ERROR' | 'NETWORK_ERROR';

interface ImportStage {
  name: string;
  progress: number;
  status: 'pending' | 'active' | 'complete' | 'error';
}

interface FieldError {
  field: string;
  message: string;
  suggestion?: string;
}

interface ValidationState {
  stage: ValidationStage;
  progress: number;
  fieldErrors: FieldError[];
  category?: ErrorCategory;
}

const PROMPT_TEMPLATE = `You are a music sequencer AI for Hyphon (a web-based DAW). 
Generate a complete song in the following JSON format.

HYPHON SONG FORMAT:
{
  "meta": {
    "title": "Song Name",
    "author": "your-name",
    "version": "1.0",
    "createdAt": "2024-03-06T12:00:00Z",
    "generator": "claude-3-opus",
    "prompt": "brief description"
  },
  "globals": {
    "tempo": 128,
    "timeSignature": [4, 4],
    "swing": 50
  },
  "tracks": {
    "synthA": {
      "notes": [
        {"step": 0, "note": "C3", "velocity": 0.8, "accent": true},
        {"step": 4, "note": "G3"},
        {"step": 8, "note": "Eb3", "accent": true},
        {"step": 12, "note": "F3"}
      ],
      "params": {
        "waveform": "303-saw",
        "filterCutoff": 3000,
        "filterResonance": 12,
        "decay": 0.4
      }
    },
    "kick": [true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false],
    "snare": [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
    "closedHat": [false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true],
    "openHat": [false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false]
  }
}

RULES:
- Steps are 0-15 for 16-step patterns or 0-31 for 32-step patterns
- Notes use format like "C3", "F#4", "Bb2"
- Drum tracks are boolean arrays (true = hit on that step)
- Tempo range: 30-300 BPM
- Swing: 0-100 (50 = no swing, higher = more shuffle)

Generate a {GENRE} song at {TEMPO} BPM with {MOOD} mood.
Return ONLY the JSON, no markdown, no explanation.`;

// ============================================================================
// EXAMPLE SONGS
// ============================================================================

const EXAMPLE_TECHNO: AISongData = {
  meta: { 
    title: "Techno Basement", 
    author: "AI Demo", 
    version: "1.0", 
    createdAt: "2024-03-06T12:00:00Z", 
    generator: "demo", 
    prompt: "Dark techno bassline" 
  },
  globals: { 
    tempo: 130, 
    timeSignature: [4, 4], 
    swing: 50 
  },
  tracks: {
    synthA: { 
      notes: [
        {step: 0, note: "C2", velocity: 0.9, accent: true}, 
        {step: 4, note: "C2"}, 
        {step: 8, note: "Eb2", accent: true}, 
        {step: 12, note: "F2"},
        {step: 16, note: "C2", accent: true},
        {step: 20, note: "Bb1"},
        {step: 24, note: "G1", accent: true},
        {step: 28, note: "C2"}
      ], 
      params: { 
        waveform: "303-saw", 
        filterCutoff: 2000, 
        filterResonance: 15, 
        decay: 0.5 
      } 
    },
    kick: [
      true, false, false, false, true, false, false, false, 
      true, false, false, false, true, false, false, false,
      true, false, false, false, true, false, false, false,
      true, false, false, false, true, false, false, false
    ],
    snare: [
      false, false, false, false, true, false, false, false, 
      false, false, false, false, true, false, false, false,
      false, false, false, false, true, false, false, false,
      false, false, false, false, true, false, false, false
    ],
    closedHat: [
      false, true, false, true, false, true, false, true, 
      false, true, false, true, false, true, false, true,
      false, true, false, true, false, true, false, true,
      false, true, false, true, false, true, false, true
    ],
    openHat: [
      false, false, false, false, false, false, false, false,
      false, false, false, false, false, false, false, false,
      false, false, false, false, false, false, false, false,
      false, false, true, false, false, false, false, false
    ],
    sampler: [
      {
        bankIndex: 0,
        steps: [
          {step: 0, note: "C4", velocity: 0.7},
          {step: 8, note: "C4", velocity: 0.5},
          {step: 16, note: "C4", velocity: 0.7},
          {step: 24, note: "C4", velocity: 0.5}
        ],
        ttsText: "Techno",
        params: { playbackSpeed: 1.0, volume: 0.8 }
      }
    ]
  }
};

const EXAMPLE_HOUSE: AISongData = {
  meta: { 
    title: "House Groove", 
    author: "AI Demo", 
    version: "1.0", 
    createdAt: "2024-03-06T12:00:00Z", 
    generator: "demo", 
    prompt: "Funky house with piano chords" 
  },
  globals: { 
    tempo: 124, 
    timeSignature: [4, 4], 
    swing: 55 
  },
  tracks: {
    synthA: { 
      notes: [
        {step: 0, note: "C4", velocity: 0.8}, 
        {step: 2, note: "E4", velocity: 0.7}, 
        {step: 4, note: "G4", velocity: 0.8}, 
        {step: 6, note: "B4", velocity: 0.7},
        {step: 8, note: "A4", velocity: 0.8},
        {step: 10, note: "C5", velocity: 0.7},
        {step: 12, note: "G4", velocity: 0.8},
        {step: 14, note: "E4", velocity: 0.7}
      ], 
      params: { 
        waveform: "square", 
        filterCutoff: 3500, 
        filterResonance: 8, 
        decay: 0.3 
      } 
    },
    synthB: {
      notes: [
        {step: 0, note: "C3", velocity: 0.9},
        {step: 8, note: "F3", velocity: 0.9},
        {step: 16, note: "C3", velocity: 0.9},
        {step: 24, note: "G3", velocity: 0.9}
      ],
      params: {
        waveform: "sawtooth",
        filterCutoff: 2800,
        filterResonance: 6,
        decay: 0.4
      }
    },
    kick: [
      true, false, false, false, false, false, true, false,
      true, false, false, false, false, false, true, false,
      true, false, false, false, false, false, true, false,
      true, false, false, false, false, false, true, false
    ],
    snare: [
      false, false, false, false, true, false, false, false,
      false, false, false, false, true, false, false, false,
      false, false, false, false, true, false, false, false,
      false, false, false, false, true, false, false, false
    ],
    closedHat: [
      true, false, true, false, true, false, true, false,
      true, false, true, false, true, false, true, false,
      true, false, true, false, true, false, true, false,
      true, false, true, false, true, false, true, false
    ],
    openHat: [
      false, false, false, false, false, false, false, false,
      false, false, true, false, false, false, false, false,
      false, false, false, false, false, false, false, false,
      true, false, false, false, false, false, false, false
    ]
  }
};

const EXAMPLE_AMBIENT: AISongData = {
  meta: { 
    title: "Ambient Drift", 
    author: "AI Demo", 
    version: "1.0", 
    createdAt: "2024-03-06T12:00:00Z", 
    generator: "demo", 
    prompt: "Ethereal ambient soundscape" 
  },
  globals: { 
    tempo: 85, 
    timeSignature: [4, 4], 
    swing: 50 
  },
  tracks: {
    synthA: { 
      notes: [
        {step: 0, note: "D4", velocity: 0.5, length: 8}, 
        {step: 8, note: "A4", velocity: 0.4, length: 8}, 
        {step: 16, note: "F4", velocity: 0.5, length: 8}, 
        {step: 24, note: "E4", velocity: 0.4, length: 8}
      ], 
      params: { 
        waveform: "sine", 
        filterCutoff: 1500, 
        filterResonance: 4, 
        attack: 0.5,
        decay: 1.0,
        sustain: 0.8,
        release: 2.0
      } 
    },
    bass2: {
      notes: [
        {step: 0, note: "D2", velocity: 0.6, length: 16},
        {step: 16, note: "A1", velocity: 0.6, length: 16}
      ],
      params: {
        waveform: "303-saw",
        filterCutoff: 800,
        filterResonance: 3,
        attack: 0.3,
        decay: 1.5
      }
    },
    closedHat: [
      false, false, false, false, false, false, false, false,
      true, false, false, false, false, false, false, false,
      false, false, false, false, false, false, false, false,
      true, false, false, false, false, false, false, false
    ],
    sampler: [
      {
        bankIndex: 0,
        steps: [
          {step: 0, note: "C4", velocity: 0.3, length: 32}
        ],
        ttsText: "floating in space",
        params: { 
          playbackSpeed: 0.7, 
          volume: 0.6,
          filterCutoff: 3000,
          filterResonance: 5
        }
      }
    ]
  }
};

const EXAMPLES = {
  techno: { name: "Techno Basic", data: EXAMPLE_TECHNO },
  house: { name: "House Groove", data: EXAMPLE_HOUSE },
  ambient: { name: "Ambient Drift", data: EXAMPLE_AMBIENT }
};

// ============================================================================
// UTILITY FUNCTIONS
// ============================================================================

/**
 * Auto-fix common JSON issues
 */
function fixCommonJsonIssues(json: string): { fixed: string; changes: string[] } {
  const changes: string[] = [];
  let fixed = json;

  // Remove markdown code fences
  const codeFenceMatch = fixed.match(/```(?:json)?\s*([\s\S]*?)```/);
  if (codeFenceMatch) {
    fixed = codeFenceMatch[1].trim();
    changes.push('Removed markdown code fences');
  }

  // Fix trailing commas
  const beforeTrailingComma = fixed;
  fixed = fixed.replace(/,(\s*[}\]])/g, '$1');
  if (fixed !== beforeTrailingComma) {
    changes.push('Fixed trailing commas');
  }

  // Fix single quotes to double quotes (basic)
  const beforeQuotes = fixed;
  fixed = fixed.replace(/'([^']*)':/g, '"$1":');
  fixed = fixed.replace(/: '([^']*)'/g, ': "$1"');
  if (fixed !== beforeQuotes) {
    changes.push('Converted single quotes to double quotes');
  }

  // Fix missing quotes around property names
  const beforePropQuotes = fixed;
  fixed = fixed.replace(/([{,]\s*)([a-zA-Z_][a-zA-Z0-9_]*)(\s*:)/g, '$1"$2"$3');
  if (fixed !== beforePropQuotes) {
    changes.push('Added quotes around property names');
  }

  return { fixed, changes };
}

/**
 * Categorize error type
 */
function categorizeError(error: string | AIImportErrorDetails): ErrorCategory {
  const errorStr = typeof error === 'string' ? error : JSON.stringify(error);
  
  if (errorStr.includes('JSON') || errorStr.includes('parse') || errorStr.includes('Unexpected')) {
    return 'JSON_SYNTAX';
  }
  if (errorStr.includes('VALIDATION') || errorStr.includes('required') || errorStr.includes('must be')) {
    return 'SCHEMA_VIOLATION';
  }
  if (errorStr.includes('CONVERSION')) {
    return 'CONVERSION_ERROR';
  }
  if (errorStr.includes('STORAGE') || errorStr.includes('upload') || errorStr.includes('network')) {
    return 'NETWORK_ERROR';
  }
  return 'SCHEMA_VIOLATION';
}

/**
 * Get error suggestions based on category
 */
function getErrorSuggestions(category: ErrorCategory): string[] {
  switch (category) {
    case 'JSON_SYNTAX':
      return [
        'Check for missing commas or brackets',
        'Ensure all strings are in double quotes',
        'Remove any trailing commas before closing braces',
        'Try the "Fix Common Issues" button'
      ];
    case 'SCHEMA_VIOLATION':
      return [
        'Verify the meta.title field exists and is a string',
        'Check that globals.tempo is a number between 30-300',
        'Ensure tracks object contains valid track data',
        'Version must be exactly "1.0"'
      ];
    case 'CONVERSION_ERROR':
      return [
        'Check note formats (e.g., "C4", "F#3")',
        'Ensure step values are within 0-31',
        'Verify velocity values are between 0-1'
      ];
    case 'NETWORK_ERROR':
      return [
        'Check your internet connection',
        'The song can still be imported locally',
        'Try uploading again later'
      ];
  }
}

/**
 * Get validation status color
 */
function getValidationColor(stage: ValidationStage): string {
  switch (stage) {
    case 'idle': return 'bg-gray-700';
    case 'parsing': return 'bg-yellow-500';
    case 'validating': return 'bg-yellow-500';
    case 'converting': return 'bg-emerald-500';
    case 'complete': return 'bg-emerald-500';
    case 'error': return 'bg-red-500';
  }
}

/**
 * Format file size
 */
function formatFileSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

// ============================================================================
// COMPONENT
// ============================================================================

interface AISongModalProps {
  isOpen: boolean;
  onClose: () => void;
  onImport: (song: SavedSongData, aiData: AISongData) => void;
  onShowToast: (message: string, type: 'success' | 'error' | 'info') => void;
  audioEngine?: unknown;
}

export function AISongModal({ isOpen, onClose, onImport, onShowToast, audioEngine }: AISongModalProps) {
  const [jsonInput, setJsonInput] = useState('');
  const [isDragging, setIsDragging] = useState(false);
  const [parsedData, setParsedData] = useState<AISongData | null>(null);
  const [validationState, setValidationState] = useState<ValidationState>({
    stage: 'idle',
    progress: 0,
    fieldErrors: []
  });
  const [isImporting, setIsImporting] = useState(false);
  const [activeTab, setActiveTab] = useState<TabType>('paste');
  const [importStages, setImportStages] = useState<ImportStage[]>([
    { name: 'Parse', progress: 0, status: 'pending' },
    { name: 'Validate', progress: 0, status: 'pending' },
    { name: 'Convert', progress: 0, status: 'pending' },
    { name: 'Upload', progress: 0, status: 'pending' },
    { name: 'Complete', progress: 0, status: 'pending' }
  ]);
  const [droppedFile, setDroppedFile] = useState<File | null>(null);
  const [showFixSuccess, setShowFixSuccess] = useState(false);
  const [copiedError, setCopiedError] = useState(false);
  
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  // Reset state when modal opens/closes
  useEffect(() => {
    if (!isOpen) {
      setJsonInput('');
      setParsedData(null);
      setValidationState({ stage: 'idle', progress: 0, fieldErrors: [] });
      setIsImporting(false);
      setActiveTab('paste');
      setImportStages([
        { name: 'Parse', progress: 0, status: 'pending' },
        { name: 'Validate', progress: 0, status: 'pending' },
        { name: 'Convert', progress: 0, status: 'pending' },
        { name: 'Upload', progress: 0, status: 'pending' },
        { name: 'Complete', progress: 0, status: 'pending' }
      ]);
      setDroppedFile(null);
      setShowFixSuccess(false);
      setCopiedError(false);
    }
  }, [isOpen]);

  // Keyboard shortcuts
  useEffect(() => {
    if (!isOpen) return;

    const handleKeyDown = (e: KeyboardEvent) => {
      // Ctrl+V to focus textarea
      if ((e.ctrlKey || e.metaKey) && e.key === 'v' && activeTab === 'paste') {
        // Let the paste happen naturally, but focus the textarea
        setTimeout(() => textareaRef.current?.focus(), 0);
      }
      // Esc to close
      if (e.key === 'Escape') {
        onClose();
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isOpen, activeTab, onClose]);

  // Handle JSON parsing and validation with progress
  const handleJsonChange = useCallback(async (value: string, skipProgress = false) => {
    setJsonInput(value);
    setParsedData(null);
    setValidationState({ stage: 'idle', progress: 0, fieldErrors: [] });
    setShowFixSuccess(false);

    if (!value.trim()) {
      setValidationState({ stage: 'idle', progress: 0, fieldErrors: [] });
      return;
    }

    if (!skipProgress) {
      setValidationState({ stage: 'parsing', progress: 25, fieldErrors: [] });
      // Small delay to show progress
      await new Promise(resolve => setTimeout(resolve, 100));
    }

    // Try to parse JSON
    const parseResult = parseAISongJSON(value);
    if (!parseResult.success) {
      const category = categorizeError(parseResult.error);
      setValidationState({
        stage: 'error',
        progress: 0,
        fieldErrors: [{ field: 'JSON', message: parseResult.error }],
        category
      });
      return;
    }

    if (!skipProgress) {
      setValidationState({ stage: 'validating', progress: 50, fieldErrors: [] });
      await new Promise(resolve => setTimeout(resolve, 100));
    }

    // Validate against schema
    const importer = new AISongImporter();
    const result = importer.convert(parseResult.data);

    if (!skipProgress) {
      setValidationState({ stage: 'converting', progress: 75, fieldErrors: [] });
      await new Promise(resolve => setTimeout(resolve, 100));
    }
    
    if (!result.success) {
      const fieldErrors: FieldError[] = [];
      const error = result.error;
      
      if (error.type === 'VALIDATION_ERROR') {
        fieldErrors.push({
          field: error.field,
          message: error.message,
          suggestion: error.field.includes('tempo') ? 'Use a value between 30-300' : undefined
        });
      } else if (error.type === 'CONVERSION_ERROR') {
        fieldErrors.push({
          field: error.track,
          message: error.details
        });
      } else if (error.type === 'INVALID_NOTE') {
        fieldErrors.push({
          field: `tracks.${error.track}`,
          message: `Invalid note: "${error.note}"`,
          suggestion: 'Use format like "C4", "F#3", "Bb2"'
        });
      } else {
        fieldErrors.push({
          field: error.type,
          message: JSON.stringify(error)
        });
      }

      const category = categorizeError(error);
      setValidationState({
        stage: 'error',
        progress: 0,
        fieldErrors,
        category
      });
      return;
    }

    setValidationState({
      stage: 'complete',
      progress: 100,
      fieldErrors: [],
      category: undefined
    });
    setParsedData(parseResult.data);
  }, []);

  // Handle file drop
  const handleDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);

    const file = e.dataTransfer.files[0];
    if (!file) return;

    if (file.type !== 'application/json' && !file.name.endsWith('.json')) {
      setValidationState({
        stage: 'error',
        progress: 0,
        fieldErrors: [{ field: 'file', message: 'Please drop a .json file' }],
        category: 'JSON_SYNTAX'
      });
      return;
    }

    setDroppedFile(file);

    const reader = new FileReader();
    reader.onload = (event) => {
      const content = event.target?.result as string;
      if (content) {
        handleJsonChange(content);
        setJsonInput(content);
      }
    };
    reader.onerror = () => {
      setValidationState({
        stage: 'error',
        progress: 0,
        fieldErrors: [{ field: 'file', message: 'Failed to read file' }],
        category: 'JSON_SYNTAX'
      });
    };
    reader.readAsText(file);
  }, [handleJsonChange]);

  // Handle file input
  const handleFileSelect = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setDroppedFile(file);

    const reader = new FileReader();
    reader.onload = (event) => {
      const content = event.target?.result as string;
      if (content) {
        handleJsonChange(content);
        setJsonInput(content);
      }
    };
    reader.readAsText(file);
  }, [handleJsonChange]);

  // Handle import with progress stages
  const handleImport = useCallback(async () => {
    if (!parsedData) return;

    setIsImporting(true);

    // Update stages progressively
    const updateStage = (index: number, status: ImportStage['status'], progress: number) => {
      setImportStages(prev => prev.map((stage, i) => 
        i === index ? { ...stage, status, progress } : 
        i < index ? { ...stage, status: 'complete', progress: 100 } :
        stage
      ));
    };

    try {
      // Stage 1: Parse
      updateStage(0, 'active', 50);
      await new Promise(resolve => setTimeout(resolve, 200));
      updateStage(0, 'complete', 100);

      // Stage 2: Validate
      updateStage(1, 'active', 50);
      const importer = new AISongImporter();
      const result = importer.convert(parsedData);
      await new Promise(resolve => setTimeout(resolve, 200));
      
      if (!result.success) {
        updateStage(1, 'error', 0);
        onShowToast(`Import failed: ${result.error.type}`, 'error');
        setIsImporting(false);
        return;
      }
      updateStage(1, 'complete', 100);

      // Stage 3: Convert
      updateStage(2, 'active', 50);
      await new Promise(resolve => setTimeout(resolve, 200));
      updateStage(2, 'complete', 100);

      // Stage 4: Upload
      updateStage(3, 'active', 50);
      const uploadResult = await importer.uploadToCloud(parsedData, result.song);
      
      if (uploadResult.success) {
        updateStage(3, 'complete', 100);
        onShowToast(`AI Song uploaded to cloud (ID: ${uploadResult.id})`, 'success');
      } else {
        updateStage(3, 'error', 0);
        onShowToast('Song imported locally (cloud upload failed)', 'info');
      }

      // Stage 5: Complete
      updateStage(4, 'complete', 100);
      await new Promise(resolve => setTimeout(resolve, 300));

      // Import into sequencer
      onImport(result.song, parsedData);
      onClose();
    } catch (error) {
      setImportStages(prev => prev.map((stage, i) => 
        i === 3 ? { ...stage, status: 'error', progress: 0 } : stage
      ));
      onShowToast(`Import error: ${error instanceof Error ? error.message : 'Unknown'}`, 'error');
    } finally {
      setIsImporting(false);
    }
  }, [parsedData, onImport, onClose, onShowToast]);

  // Copy template to clipboard
  const copyTemplate = useCallback(() => {
    navigator.clipboard.writeText(PROMPT_TEMPLATE);
    onShowToast('Prompt template copied!', 'success');
  }, [onShowToast]);

  // Load example
  const loadExample = useCallback((exampleKey: keyof typeof EXAMPLES) => {
    const example = EXAMPLES[exampleKey];
    const json = JSON.stringify(example.data, null, 2);
    setJsonInput(json);
    handleJsonChange(json, true);
    onShowToast(`Loaded "${example.name}" example`, 'info');
  }, [handleJsonChange, onShowToast]);

  // Fix common issues
  const handleFixCommonIssues = useCallback(async () => {
    const { fixed, changes } = fixCommonJsonIssues(jsonInput);
    if (changes.length > 0) {
      setJsonInput(fixed);
      await handleJsonChange(fixed, true);
      setShowFixSuccess(true);
      setTimeout(() => setShowFixSuccess(false), 3000);
    }
  }, [jsonInput, handleJsonChange]);

  // Copy error report
  const copyErrorReport = useCallback(() => {
    const report = {
      timestamp: new Date().toISOString(),
      category: validationState.category,
      errors: validationState.fieldErrors,
      inputPreview: jsonInput.substring(0, 500) + (jsonInput.length > 500 ? '...' : '')
    };
    navigator.clipboard.writeText(JSON.stringify(report, null, 2));
    setCopiedError(true);
    setTimeout(() => setCopiedError(false), 2000);
  }, [validationState, jsonInput]);

  // Calculate track statistics
  const trackStats = useMemo(() => {
    if (!parsedData) return null;
    
    const stats = {
      totalNotes: 0,
      noteCounts: {} as Record<string, number>,
      avgVelocity: 0,
      velocitySum: 0,
      noteCount: 0,
      duration: 0
    };

    // Count notes in melodic tracks
    ['synthA', 'synthB', 'bass2'].forEach(track => {
      const trackData = parsedData.tracks[track as keyof typeof parsedData.tracks];
      if (trackData && 'notes' in trackData && Array.isArray(trackData.notes)) {
        const count = trackData.notes.length;
        stats.noteCounts[track] = count;
        stats.totalNotes += count;
        trackData.notes.forEach((note: { velocity?: number }) => {
          if (note.velocity) {
            stats.velocitySum += note.velocity;
            stats.noteCount++;
          }
        });
      }
    });

    // Count drum hits
    ['kick', 'snare', 'closedHat', 'openHat'].forEach(track => {
      const trackData = parsedData.tracks[track as keyof typeof parsedData.tracks];
      if (Array.isArray(trackData)) {
        const count = trackData.filter(Boolean).length;
        stats.noteCounts[track] = count;
        stats.totalNotes += count;
      }
    });

    // Count sampler notes
    if (parsedData.tracks.sampler) {
      parsedData.tracks.sampler.forEach((bank, i) => {
        const count = bank.steps.length;
        stats.noteCounts[`sampler${bank.bankIndex}`] = count;
        stats.totalNotes += count;
        bank.steps.forEach((note: { velocity?: number }) => {
          if (note.velocity) {
            stats.velocitySum += note.velocity;
            stats.noteCount++;
          }
        });
      });
    }

    stats.avgVelocity = stats.noteCount > 0 ? stats.velocitySum / stats.noteCount : 0;

    // Estimate duration
    const stepsPerPattern = 32;
    const secondsPerStep = 60 / parsedData.globals.tempo / 4;
    stats.duration = stepsPerPattern * secondsPerStep;

    return stats;
  }, [parsedData]);

  // Generate pattern grid for preview
  const patternGrid = useMemo(() => {
    if (!parsedData) return null;

    const tracks = ['synthA', 'synthB', 'bass2', 'kick', 'snare', 'closedHat', 'openHat', 'sampler0'];
    const grid: boolean[][] = [];

    tracks.forEach((trackName, trackIdx) => {
      const row: boolean[] = Array(32).fill(false);
      
      if (trackName === 'sampler0' && parsedData.tracks.sampler?.[0]) {
        parsedData.tracks.sampler[0].steps.forEach((note: { step: number }) => {
          if (note.step >= 0 && note.step < 32) row[note.step] = true;
        });
      } else if (trackName in parsedData.tracks) {
        const trackData = parsedData.tracks[trackName as keyof typeof parsedData.tracks];
        if (trackData && 'notes' in trackData && Array.isArray(trackData.notes)) {
          trackData.notes.forEach((note: { step: number }) => {
            if (note.step >= 0 && note.step < 32) row[note.step] = true;
          });
        } else if (Array.isArray(trackData)) {
          trackData.forEach((hit, i) => {
            if (i < 32 && hit) row[i] = true;
          });
        }
      }
      
      grid.push(row);
    });

    return { tracks, grid };
  }, [parsedData]);

  if (!isOpen) return null;

  const hasErrors = validationState.stage === 'error' && validationState.fieldErrors.length > 0;
  const isValid = validationState.stage === 'complete' && parsedData !== null;

  return (
    <div 
      className="fixed inset-0 bg-black/70 backdrop-blur-sm z-50 flex items-center justify-center p-4"
      onClick={(e) => e.target === e.currentTarget && onClose()}
    >
      <div className="bg-[#0f1115] border border-emerald-500/30 rounded-xl shadow-[0_0_60px_rgba(16,185,129,0.2)] w-full max-w-3xl max-h-[90vh] flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between p-4 border-b border-gray-800">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-lg bg-emerald-500/10 border border-emerald-500/30 flex items-center justify-center">
              <span className="text-2xl">🤖</span>
            </div>
            <div>
              <h2 className="text-lg font-bold text-white">Import AI Song</h2>
              <p className="text-xs text-gray-400">Import songs from Claude, Gemini, Jules, Copilot, etc.</p>
            </div>
          </div>
          <button 
            onClick={onClose}
            className="w-8 h-8 rounded-lg bg-gray-800 hover:bg-gray-700 text-gray-400 hover:text-white transition-all"
            title="Close (Esc)"
          >
            ✕
          </button>
        </div>

        {/* Validation Status Bar */}
        <div className={`h-1 w-full transition-colors duration-300 ${getValidationColor(validationState.stage)}`}>
          <div 
            className="h-full bg-white/30 transition-all duration-300"
            style={{ width: `${validationState.progress}%` }}
          />
        </div>

        {/* Tabs */}
        <div className="flex border-b border-gray-800">
          <button
            onClick={() => setActiveTab('paste')}
            className={`flex-1 py-3 text-sm font-medium transition-all ${
              activeTab === 'paste' 
                ? 'text-emerald-400 border-b-2 border-emerald-500 bg-emerald-500/5' 
                : 'text-gray-400 hover:text-gray-200 hover:bg-gray-800/50'
            }`}
          >
            📋 Paste JSON
          </button>
          <button
            onClick={() => setActiveTab('template')}
            className={`flex-1 py-3 text-sm font-medium transition-all ${
              activeTab === 'template' 
                ? 'text-emerald-400 border-b-2 border-emerald-500 bg-emerald-500/5' 
                : 'text-gray-400 hover:text-gray-200 hover:bg-gray-800/50'
            }`}
          >
            📝 Prompt Template
          </button>
          <button
            onClick={() => isValid && setActiveTab('preview')}
            disabled={!isValid}
            className={`flex-1 py-3 text-sm font-medium transition-all ${
              activeTab === 'preview' 
                ? 'text-emerald-400 border-b-2 border-emerald-500 bg-emerald-500/5' 
                : !isValid
                  ? 'text-gray-600 cursor-not-allowed'
                  : 'text-gray-400 hover:text-gray-200 hover:bg-gray-800/50'
            }`}
          >
            👁️ Preview {!isValid && '(needs valid JSON)'}
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-auto p-4">
          {activeTab === 'paste' ? (
            <div className="space-y-4">
              {/* Example Buttons */}
              <div className="flex flex-wrap gap-2">
                <span className="text-xs text-gray-500 py-2">Try with example:</span>
                {(Object.keys(EXAMPLES) as Array<keyof typeof EXAMPLES>).map(key => (
                  <button
                    key={key}
                    onClick={() => loadExample(key)}
                    className="px-3 py-1.5 bg-gray-800 hover:bg-gray-700 text-gray-300 text-xs rounded transition-all border border-gray-700 hover:border-emerald-500/50"
                  >
                    {EXAMPLES[key].name}
                  </button>
                ))}
              </div>

              {/* Drop Zone */}
              <div
                onDragOver={(e) => { e.preventDefault(); setIsDragging(true); }}
                onDragLeave={() => setIsDragging(false)}
                onDrop={handleDrop}
                className={`border-2 border-dashed rounded-lg p-6 text-center transition-all ${
                  isDragging 
                    ? 'border-emerald-500 bg-emerald-500/10' 
                    : 'border-gray-700 bg-gray-900/50 hover:border-gray-600'
                }`}
              >
                <div className="text-3xl mb-2">📁</div>
                <p className="text-sm text-gray-400 mb-2">Drag & drop a .json file here</p>
                <p className="text-xs text-gray-500">or</p>
                <button
                  onClick={() => fileInputRef.current?.click()}
                  className="mt-2 px-4 py-2 bg-gray-800 hover:bg-gray-700 text-gray-300 text-xs rounded transition-all"
                >
                  Browse Files
                </button>
                <input
                  ref={fileInputRef}
                  type="file"
                  accept=".json,application/json"
                  onChange={handleFileSelect}
                  className="hidden"
                />
                {droppedFile && (
                  <div className="mt-3 flex items-center justify-center gap-2 text-xs text-emerald-400">
                    <span>📄</span>
                    <span>{droppedFile.name}</span>
                    <span className="text-gray-500">({formatFileSize(droppedFile.size)})</span>
                  </div>
                )}
              </div>

              {/* Textarea */}
              <div>
                <div className="flex items-center justify-between mb-2">
                  <label className="text-xs text-gray-500">Or paste JSON directly:</label>
                  <span className="text-xs text-gray-600">Press Ctrl+V to focus</span>
                </div>
                <textarea
                  ref={textareaRef}
                  value={jsonInput}
                  onChange={(e) => handleJsonChange(e.target.value)}
                  placeholder={`{\n  "meta": {\n    "title": "My AI Song",\n    "author": "claude",\n    "version": "1.0",\n    ...\n  }\n}`}
                  className="w-full h-40 bg-[#0a0c10] border border-gray-800 rounded-lg p-3 text-xs font-mono text-gray-300 resize-none focus:border-emerald-500/50 focus:outline-none"
                />
              </div>

              {/* Validation Progress */}
              {validationState.stage !== 'idle' && validationState.stage !== 'error' && validationState.stage !== 'complete' && (
                <div className="flex items-center gap-2 text-xs text-yellow-400">
                  <span className="animate-spin">⏳</span>
                  <span>
                    {validationState.stage === 'parsing' && 'Checking JSON syntax...'}
                    {validationState.stage === 'validating' && 'Validating schema...'}
                    {validationState.stage === 'converting' && 'Converting to Hyphon format...'}
                  </span>
                </div>
              )}

              {/* Error Display */}
              {hasErrors && (
                <div className="p-4 bg-red-950/30 border border-red-900/50 rounded-lg">
                  <div className="flex items-center justify-between mb-2">
                    <div className="flex items-center gap-2 text-red-400">
                      <span>⚠️</span>
                      <span className="text-sm font-medium">
                        {validationState.category === 'JSON_SYNTAX' && 'JSON Syntax Error'}
                        {validationState.category === 'SCHEMA_VIOLATION' && 'Schema Violation'}
                        {validationState.category === 'CONVERSION_ERROR' && 'Conversion Error'}
                        {validationState.category === 'NETWORK_ERROR' && 'Network Error'}
                      </span>
                    </div>
                    <div className="flex gap-2">
                      {validationState.category === 'JSON_SYNTAX' && (
                        <button
                          onClick={handleFixCommonIssues}
                          className="px-3 py-1 bg-red-900/50 hover:bg-red-800/50 text-red-300 text-xs rounded transition-all"
                        >
                          🔧 Fix Common Issues
                        </button>
                      )}
                      <button
                        onClick={copyErrorReport}
                        className="px-3 py-1 bg-gray-800 hover:bg-gray-700 text-gray-400 text-xs rounded transition-all"
                      >
                        {copiedError ? '✓ Copied!' : '📋 Copy Error Report'}
                      </button>
                    </div>
                  </div>
                  
                  {showFixSuccess && (
                    <div className="mb-3 p-2 bg-emerald-900/30 border border-emerald-700/50 rounded text-emerald-400 text-xs">
                      ✓ Common issues fixed! Please review the changes.
                    </div>
                  )}

                  {/* Field-level errors */}
                  <div className="space-y-2 mt-3">
                    {validationState.fieldErrors.map((error, idx) => (
                      <div key={idx} className="text-xs">
                        <div className="text-red-400 font-mono">{error.field}: {error.message}</div>
                        {error.suggestion && (
                          <div className="text-gray-500 ml-4">💡 {error.suggestion}</div>
                        )}
                      </div>
                    ))}
                  </div>

                  {/* Suggestions */}
                  {validationState.category && (
                    <div className="mt-3 pt-3 border-t border-red-900/30">
                      <p className="text-xs text-gray-500 mb-1">Suggestions:</p>
                      <ul className="text-xs text-gray-400 space-y-0.5 list-disc list-inside">
                        {getErrorSuggestions(validationState.category).map((suggestion, idx) => (
                          <li key={idx}>{suggestion}</li>
                        ))}
                      </ul>
                    </div>
                  )}
                </div>
              )}

              {/* Success Display */}
              {isValid && parsedData && (
                <div className="p-4 bg-emerald-950/30 border border-emerald-900/50 rounded-lg">
                  <div className="flex items-center gap-2 text-emerald-400 mb-3">
                    <span>✓</span>
                    <span className="text-sm font-medium">Valid AI Song</span>
                  </div>
                  <div className="grid grid-cols-2 gap-2 text-xs">
                    <p><span className="text-gray-500">Title:</span> <span className="text-emerald-400/70">{parsedData.meta.title}</span></p>
                    <p><span className="text-gray-500">Author:</span> <span className="text-emerald-400/70">{parsedData.meta.author}</span></p>
                    <p><span className="text-gray-500">Tempo:</span> <span className="text-emerald-400/70">{parsedData.globals.tempo} BPM</span></p>
                    <p><span className="text-gray-500">Generator:</span> <span className="text-emerald-400/70">{parsedData.meta.generator}</span></p>
                    <p className="col-span-2"><span className="text-gray-500">Tracks:</span> <span className="text-emerald-400/70">{Object.keys(parsedData.tracks).join(', ')}</span></p>
                  </div>
                </div>
              )}
            </div>
          ) : activeTab === 'template' ? (
            <div className="space-y-4">
              <div className="p-4 bg-gray-900/50 rounded-lg">
                <p className="text-sm text-gray-300 mb-4">
                  Copy this prompt template and paste it into your AI assistant (Claude, Gemini, Jules, Copilot, etc.).
                  Customize the genre, tempo, and mood as desired.
                </p>
                <button
                  onClick={copyTemplate}
                  className="mb-3 px-4 py-2 bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-medium rounded transition-all flex items-center gap-2"
                >
                  <span>📋</span> Copy Template to Clipboard
                </button>
                <pre className="bg-[#0a0c10] border border-gray-800 rounded-lg p-4 text-xs text-gray-400 overflow-x-auto whitespace-pre-wrap font-mono">
                  {PROMPT_TEMPLATE}
                </pre>
              </div>
              
              <div className="p-4 bg-blue-950/20 border border-blue-900/30 rounded-lg">
                <h3 className="text-sm font-medium text-blue-400 mb-2">🎯 Tips for Best Results</h3>
                <ul className="text-xs text-blue-400/70 space-y-1 list-disc list-inside">
                  <li>Be specific about genre (techno, house, drum & bass, etc.)</li>
                  <li>Mention desired energy level (chill, driving, aggressive)</li>
                  <li>Reference specific artists or tracks for style</li>
                  <li>Specify complexity (minimal, layered, complex)</li>
                  <li>Most AIs work best with clear, structured prompts</li>
                </ul>
              </div>
            </div>
          ) : (
            /* Preview Tab */
            <div className="space-y-4">
              {parsedData && trackStats && patternGrid && (
                <>
                  {/* Song Info */}
                  <div className="p-4 bg-gray-900/50 rounded-lg">
                    <h3 className="text-sm font-medium text-emerald-400 mb-3">{parsedData.meta.title}</h3>
                    <div className="grid grid-cols-3 gap-4 text-xs">
                      <div>
                        <span className="text-gray-500 block">Tempo</span>
                        <span className="text-white">{parsedData.globals.tempo} BPM</span>
                      </div>
                      <div>
                        <span className="text-gray-500 block">Time Signature</span>
                        <span className="text-white">{parsedData.globals.timeSignature.join('/')}</span>
                      </div>
                      <div>
                        <span className="text-gray-500 block">Est. Duration</span>
                        <span className="text-white">{trackStats.duration.toFixed(1)}s</span>
                      </div>
                    </div>
                  </div>

                  {/* Pattern Grid */}
                  <div className="p-4 bg-gray-900/50 rounded-lg">
                    <h3 className="text-sm font-medium text-gray-300 mb-3">Pattern Preview (8 tracks × 32 steps)</h3>
                    <div className="overflow-x-auto">
                      <div className="inline-block">
                        {patternGrid.grid.map((row, trackIdx) => (
                          <div key={trackIdx} className="flex items-center gap-1 mb-1">
                            <span className="w-20 text-xs text-gray-500 text-right mr-2">
                              {patternGrid.tracks[trackIdx]}
                            </span>
                            <div className="flex gap-0.5">
                              {row.map((active, stepIdx) => (
                                <div
                                  key={stepIdx}
                                  className={`w-2 h-4 rounded-sm ${
                                    active 
                                      ? 'bg-emerald-500' 
                                      : stepIdx % 4 === 0 
                                        ? 'bg-gray-700' 
                                        : 'bg-gray-800'
                                  }`}
                                  title={`Step ${stepIdx}`}
                                />
                              ))}
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>

                  {/* Track Statistics */}
                  <div className="p-4 bg-gray-900/50 rounded-lg">
                    <h3 className="text-sm font-medium text-gray-300 mb-3">Track Statistics</h3>
                    <div className="grid grid-cols-2 gap-3">
                      <div className="text-xs">
                        <span className="text-gray-500">Total Notes/Events:</span>
                        <span className="text-white ml-2">{trackStats.totalNotes}</span>
                      </div>
                      <div className="text-xs">
                        <span className="text-gray-500">Average Velocity:</span>
                        <span className="text-white ml-2">{(trackStats.avgVelocity * 100).toFixed(0)}%</span>
                      </div>
                    </div>
                    <div className="mt-3 space-y-1">
                      {Object.entries(trackStats.noteCounts).map(([track, count]) => (
                        <div key={track} className="flex items-center gap-2 text-xs">
                          <span className="w-20 text-gray-500">{track}:</span>
                          <div className="flex-1 h-2 bg-gray-800 rounded-full overflow-hidden">
                            <div 
                              className="h-full bg-emerald-500/50 rounded-full"
                              style={{ width: `${Math.min(100, (count / 16) * 100)}%` }}
                            />
                          </div>
                          <span className="text-gray-400 w-8 text-right">{count}</span>
                        </div>
                      ))}
                    </div>
                  </div>

                  {/* Audio Preview */}
                  {audioEngine && (
                    <div className="p-4 bg-gray-900/50 rounded-lg">
                      <div className="flex items-center justify-between">
                        <div>
                          <h3 className="text-sm font-medium text-gray-300">Audio Preview</h3>
                          <p className="text-xs text-gray-500">Listen to the pattern before importing</p>
                        </div>
                        <button
                          className="px-4 py-2 bg-emerald-600 hover:bg-emerald-500 text-white text-sm font-medium rounded transition-all flex items-center gap-2"
                          onClick={() => onShowToast('Audio preview coming soon!', 'info')}
                        >
                          <span>▶</span> Play Preview
                        </button>
                      </div>
                    </div>
                  )}
                </>
              )}
            </div>
          )}
        </div>

        {/* Progress Bar (shown during import) */}
        {isImporting && (
          <div className="px-4 py-3 border-t border-gray-800 bg-gray-900/30">
            <div className="space-y-2">
              {importStages.map((stage, idx) => (
                <div key={stage.name} className="flex items-center gap-3">
                  <div className="w-16 text-xs text-gray-500">{stage.name}</div>
                  <div className="flex-1 h-2 bg-gray-800 rounded-full overflow-hidden">
                    <div 
                      className={`h-full rounded-full transition-all duration-300 ${
                        stage.status === 'error' ? 'bg-red-500' :
                        stage.status === 'complete' ? 'bg-emerald-500' :
                        stage.status === 'active' ? 'bg-yellow-500' :
                        'bg-gray-700'
                      }`}
                      style={{ width: `${stage.progress}%` }}
                    />
                  </div>
                  <div className="w-6 text-xs">
                    {stage.status === 'complete' && <span className="text-emerald-500">✓</span>}
                    {stage.status === 'error' && <span className="text-red-500">✗</span>}
                    {stage.status === 'active' && <span className="text-yellow-500 animate-pulse">⋯</span>}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Footer */}
        <div className="flex items-center justify-between p-4 border-t border-gray-800">
          <div className="text-xs text-gray-500">
            {validationState.stage === 'parsing' && 'Checking JSON syntax...'}
            {validationState.stage === 'validating' && 'Validating schema...'}
            {validationState.stage === 'converting' && 'Converting to Hyphon format...'}
            {validationState.stage === 'complete' && '✓ Ready to import'}
            {validationState.stage === 'error' && `✗ ${validationState.fieldErrors.length} error(s) found`}
            {validationState.stage === 'idle' && (jsonInput ? 'Validating...' : 'Paste or drop JSON to begin')}
          </div>
          <div className="flex gap-2">
            <button
              onClick={onClose}
              disabled={isImporting}
              className="px-4 py-2 bg-gray-800 hover:bg-gray-700 text-gray-300 text-xs font-medium rounded transition-all disabled:opacity-50"
            >
              Cancel
            </button>
            <button
              onClick={handleImport}
              disabled={!parsedData || isImporting}
              className={`px-4 py-2 text-xs font-medium rounded transition-all flex items-center gap-2 ${
                parsedData && !isImporting
                  ? 'bg-emerald-600 hover:bg-emerald-500 text-white'
                  : 'bg-gray-700 text-gray-500 cursor-not-allowed'
              }`}
            >
              {isImporting ? (
                <>
                  <span className="animate-spin">⏳</span>
                  Importing...
                </>
              ) : (
                <>
                  <span>🎵</span>
                  Import Song
                </>
              )}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

export default AISongModal;
