/**
 * AISongModal - Import AI-generated songs
 * 
 * A production-ready modal dialog for importing songs generated by external AI systems
 * (Claude, Gemini, Jules, Copilot, Grok, etc.)
 * 
 * Features:
 * - Paste JSON directly with real-time validation
 * - Drag & drop .json files with animated feedback
 * - Multi-file support with individual remove buttons
 * - Color-coded validation states (idle/validating/valid/error)
 * - Keyboard shortcuts (Ctrl+V, Esc, Ctrl+Enter, Tab)
 * - Toast integration for user feedback
 * - 3 demo songs (Techno Acid, House Groove, Drum & Bass)
 * - Loading skeletons and smooth transitions
 * - Mobile-responsive design
 */

import React, { useState, useRef, useCallback, useEffect, useMemo } from 'react';
import {
  AISongImporter,
  parseAISongJSON,
  type AISongData,
  type AIImportResultType,
  type AIImportErrorDetails
} from '../importers/ai-song';
import type { SavedSongData } from '../types';
import type { TabType, ValidationStage, ErrorCategory, ImportStage, TrackStats, FieldError, ValidationState, DroppedFile, AISongModalProps } from '../types/aiSongModal';
import { PROMPT_TEMPLATE, EXAMPLES } from '../constants/aiSongExamples';
import { generateId, fixCommonJsonIssues, categorizeError, getErrorSuggestions, getValidationColor, getTextareaBorderColor, formatFileSize, getFileIcon } from '../utils/aiSongUtils';
import { PreviewSkeleton } from './ai-song/PreviewSkeleton';
import { Tooltip } from './ai-song/Tooltip';





// ============================================================================
// MAIN COMPONENT
// ============================================================================

export const AISongModal = React.memo(function AISongModal({ isOpen, onClose, onImport, onShowToast, audioEngine }: AISongModalProps): React.ReactElement | null {
  const [jsonInput, setJsonInput] = useState('');
  const [isDragging, setIsDragging] = useState(false);
  const [dragCounter, setDragCounter] = useState(0);
  const [parsedData, setParsedData] = useState<AISongData | null>(null);
  const [validationState, setValidationState] = useState<ValidationState>({
    stage: 'idle',
    progress: 0,
    fieldErrors: []
  });
  const [isImporting, setIsImporting] = useState(false);
  const [activeTab, setActiveTab] = useState<TabType>('paste');
  const [importStages, setImportStages] = useState<ImportStage[]>([
    { name: 'Parse', progress: 0, status: 'pending' },
    { name: 'Validate', progress: 0, status: 'pending' },
    { name: 'Convert', progress: 0, status: 'pending' },
    { name: 'Upload', progress: 0, status: 'pending' },
    { name: 'Complete', progress: 0, status: 'pending' }
  ]);
  const [droppedFiles, setDroppedFiles] = useState<DroppedFile[]>([]);
  const [showFixSuccess, setShowFixSuccess] = useState(false);
  const [copiedError, setCopiedError] = useState(false);
  const [isPreviewLoading, setIsPreviewLoading] = useState(false);
  const [hasUnsavedChanges, setHasUnsavedChanges] = useState(false);
  const [showCloseConfirm, setShowCloseConfirm] = useState(false);
  
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const modalRef = useRef<HTMLDivElement>(null);

  // Reset state when modal opens/closes
  useEffect(() => {
    if (!isOpen) {
      setJsonInput('');
      setParsedData(null);
      setValidationState({ stage: 'idle', progress: 0, fieldErrors: [] });
      setIsImporting(false);
      setActiveTab('paste');
      setImportStages([
        { name: 'Parse', progress: 0, status: 'pending' },
        { name: 'Validate', progress: 0, status: 'pending' },
        { name: 'Convert', progress: 0, status: 'pending' },
        { name: 'Upload', progress: 0, status: 'pending' },
        { name: 'Complete', progress: 0, status: 'pending' }
      ]);
      setDroppedFiles([]);
      setShowFixSuccess(false);
      setCopiedError(false);
      setIsPreviewLoading(false);
      setHasUnsavedChanges(false);
      setShowCloseConfirm(false);
      setDragCounter(0);
    }
  }, [isOpen]);

  // Track unsaved changes
  useEffect(() => {
    if (jsonInput.trim() || droppedFiles.length > 0) {
      setHasUnsavedChanges(true);
    }
  }, [jsonInput, droppedFiles]);

  // Keyboard shortcuts
  useEffect(() => {
    if (!isOpen) return;

    const handleKeyDown = (e: KeyboardEvent) => {
      // Ctrl+V / Cmd+V to focus textarea
      if ((e.ctrlKey || e.metaKey) && e.key === 'v' && activeTab === 'paste') {
        e.preventDefault();
        textareaRef.current?.focus();
        // Let the paste happen naturally after focusing
        setTimeout(() => {
          onShowToast('📋 Pasted to editor', 'info');
        }, 100);
      }
      
      // Esc to close (with confirmation if unsaved)
      if (e.key === 'Escape') {
        if (hasUnsavedChanges && !showCloseConfirm) {
          e.preventDefault();
          setShowCloseConfirm(true);
          setTimeout(() => setShowCloseConfirm(false), 3000);
        } else {
          handleClose();
        }
      }

      // Ctrl+Enter to trigger import (if valid)
      if ((e.ctrlKey || e.metaKey) && e.key === 'Enter' && parsedData && !isImporting) {
        e.preventDefault();
        handleImport();
      }

      // Tab to navigate between tabs
      if (e.key === 'Tab' && !e.shiftKey && e.target === document.activeElement) {
        // Only handle tab navigation when not in textarea
        if (document.activeElement !== textareaRef.current) {
          e.preventDefault();
          const tabs: TabType[] = ['paste', 'template', 'preview'];
          const currentIndex = tabs.indexOf(activeTab);
          const nextIndex = (currentIndex + 1) % tabs.length;
          // Only navigate to preview if valid
          if (tabs[nextIndex] === 'preview' && !parsedData) {
            setActiveTab('paste');
          } else {
            setActiveTab(tabs[nextIndex]);
          }
        }
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isOpen, activeTab, hasUnsavedChanges, showCloseConfirm, parsedData, isImporting, onShowToast]);

  // Handle close with confirmation
  const handleClose = useCallback(() => {
    if (hasUnsavedChanges) {
      setShowCloseConfirm(true);
      setTimeout(() => setShowCloseConfirm(false), 3000);
      return;
    }
    onClose();
  }, [hasUnsavedChanges, onClose]);

  // Confirm close
  const confirmClose = useCallback(() => {
    setShowCloseConfirm(false);
    setHasUnsavedChanges(false);
    onClose();
  }, [onClose]);

  // Handle JSON parsing and validation with progress
  const handleJsonChange = useCallback(async (value: string, skipProgress = false) => {
    setJsonInput(value);
    setParsedData(null);
    setValidationState({ stage: 'idle', progress: 0, fieldErrors: [] });
    setShowFixSuccess(false);

    if (!value.trim()) {
      setValidationState({ stage: 'idle', progress: 0, fieldErrors: [] });
      return;
    }

    if (!skipProgress) {
      setValidationState({ stage: 'parsing', progress: 25, fieldErrors: [] });
      onShowToast('ℹ Validating...', 'info');
      // Small delay to show progress
      await new Promise(resolve => setTimeout(resolve, 100));
    }

    // Try to parse JSON
    const parseResult = parseAISongJSON(value);
    if (!parseResult.success) {
      const category = categorizeError(parseResult.error);
      setValidationState({
        stage: 'error',
        progress: 0,
        fieldErrors: [{ field: 'JSON', message: parseResult.error }],
        category
      });
      onShowToast(`✗ ${parseResult.error}`, 'error');
      return;
    }

    if (!skipProgress) {
      setValidationState({ stage: 'validating', progress: 50, fieldErrors: [] });
      await new Promise(resolve => setTimeout(resolve, 100));
    }

    // Validate against schema
    const importer = new AISongImporter();
    const result = importer.convert(parseResult.data);

    if (!skipProgress) {
      setValidationState({ stage: 'converting', progress: 75, fieldErrors: [] });
      await new Promise(resolve => setTimeout(resolve, 100));
    }
    
    if (!result.success) {
      const fieldErrors: FieldError[] = [];
      const error = result.error;
      
      if (error.type === 'VALIDATION_ERROR') {
        fieldErrors.push({
          field: error.field,
          message: error.message,
          suggestion: error.field.includes('tempo') ? 'Use a value between 30-300' : undefined
        });
      } else if (error.type === 'CONVERSION_ERROR') {
        fieldErrors.push({
          field: error.track,
          message: error.details
        });
      } else if (error.type === 'INVALID_NOTE') {
        fieldErrors.push({
          field: `tracks.${error.track}`,
          message: `Invalid note: "${error.note}"`,
          suggestion: 'Use format like "C4", "F#3", "Bb2"'
        });
      } else {
        fieldErrors.push({
          field: error.type,
          message: JSON.stringify(error)
        });
      }

      const category = categorizeError(error);
      setValidationState({
        stage: 'error',
        progress: 0,
        fieldErrors,
        category
      });
      onShowToast(`✗ Import failed: ${error.type}`, 'error');
      return;
    }

    setValidationState({
      stage: 'complete',
      progress: 100,
      fieldErrors: [],
      category: undefined
    });
    setParsedData(parseResult.data);
    onShowToast(`✓ Valid: "${parseResult.data.meta.title}"`, 'success');
  }, [onShowToast]);

  // Handle drag enter/leave with counter for nested elements
  const handleDragEnter = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setDragCounter(prev => prev + 1);
    setIsDragging(true);
  }, []);

  const handleDragLeave = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setDragCounter(prev => {
      const newCount = prev - 1;
      if (newCount <= 0) {
        setIsDragging(false);
        return 0;
      }
      return newCount;
    });
  }, []);

  // Handle file drop - support multiple files
  const handleDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
    setDragCounter(0);

    const files = Array.from(e.dataTransfer.files);
    if (files.length === 0) return;

    // Filter to only JSON files
    const jsonFiles = files.filter(file => 
      file.type === 'application/json' || file.name.endsWith('.json')
    );

    if (jsonFiles.length === 0) {
      setValidationState({
        stage: 'error',
        progress: 0,
        fieldErrors: [{ field: 'file', message: 'Please drop .json files only' }],
        category: 'JSON_SYNTAX'
      });
      onShowToast('✗ Only .json files are supported', 'error');
      return;
    }

    // Process each file
    jsonFiles.forEach((file, index) => {
      const reader = new FileReader();
      const fileId = generateId();
      
      reader.onload = (event) => {
        const content = event.target?.result as string;
        if (content) {
          setDroppedFiles(prev => [...prev, { file, id: fileId, content }]);
          // If first file, also load it into the textarea
          if (index === 0) {
            handleJsonChange(content);
            setJsonInput(content);
          }
        }
      };
      
      reader.onerror = () => {
        onShowToast(`✗ Failed to read ${file.name}`, 'error');
      };
      
      reader.readAsText(file);
    });

    onShowToast(`ℹ Uploading ${jsonFiles.length} file(s)...`, 'info');
  }, [handleJsonChange, onShowToast]);

  // Remove a dropped file
  const removeDroppedFile = useCallback((id: string) => {
    setDroppedFiles(prev => {
      const filtered = prev.filter(f => f.id !== id);
      // If removing the active file (first one), clear textarea
      if (prev[0]?.id === id && filtered.length > 0) {
        const nextFile = filtered[0];
        if (nextFile.content) {
          setJsonInput(nextFile.content);
          handleJsonChange(nextFile.content);
        }
      } else if (filtered.length === 0) {
        setJsonInput('');
        setParsedData(null);
        setValidationState({ stage: 'idle', progress: 0, fieldErrors: [] });
      }
      return filtered;
    });
  }, [handleJsonChange]);

  // Handle file input - support multiple
  const handleFileSelect = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(e.target.files || []);
    if (files.length === 0) return;

    files.forEach((file, index) => {
      const reader = new FileReader();
      const fileId = generateId();
      
      reader.onload = (event) => {
        const content = event.target?.result as string;
        if (content) {
          setDroppedFiles(prev => [...prev, { file, id: fileId, content }]);
          if (index === 0) {
            handleJsonChange(content);
            setJsonInput(content);
          }
        }
      };
      
      reader.readAsText(file);
    });

    // Reset input so same file can be selected again
    e.target.value = '';
  }, [handleJsonChange]);

  // Handle import with progress stages
  const handleImport = useCallback(async () => {
    if (!parsedData) return;

    setIsImporting(true);
    onShowToast('ℹ Uploading to cloud...', 'info');

    // Update stages progressively
    const updateStage = (index: number, status: ImportStage['status'], progress: number) => {
      setImportStages(prev => prev.map((stage, i) => 
        i === index ? { ...stage, status, progress } : 
        i < index ? { ...stage, status: 'complete', progress: 100 } :
        stage
      ));
    };

    try {
      // Stage 1: Parse
      updateStage(0, 'active', 50);
      await new Promise(resolve => setTimeout(resolve, 200));
      updateStage(0, 'complete', 100);

      // Stage 2: Validate
      updateStage(1, 'active', 50);
      const importer = new AISongImporter();
      const result = importer.convert(parsedData);
      await new Promise(resolve => setTimeout(resolve, 200));
      
      if (!result.success) {
        updateStage(1, 'error', 0);
        onShowToast(`✗ Import failed: ${result.error.type}`, 'error');
        setIsImporting(false);
        return;
      }
      updateStage(1, 'complete', 100);

      // Stage 3: Convert
      updateStage(2, 'active', 50);
      await new Promise(resolve => setTimeout(resolve, 200));
      updateStage(2, 'complete', 100);

      // Stage 4: Upload
      updateStage(3, 'active', 50);
      const uploadResult = await importer.uploadToCloud(parsedData, result.song);
      
      if (uploadResult.success) {
        updateStage(3, 'complete', 100);
        onShowToast(`✓ Song '${parsedData.meta.title}' uploaded to cloud`, 'success');
      } else {
        updateStage(3, 'error', 0);
        onShowToast('ℹ Song imported locally (cloud upload failed)', 'info');
      }

      // Stage 5: Complete
      updateStage(4, 'complete', 100);
      await new Promise(resolve => setTimeout(resolve, 300));

      // Import into sequencer
      onImport(result.song, parsedData);
      onShowToast(`✓ Song '${parsedData.meta.title}' imported successfully`, 'success');
      onClose();
    } catch (error) {
      setImportStages(prev => prev.map((stage, i) => 
        i === 3 ? { ...stage, status: 'error', progress: 0 } : stage
      ));
      onShowToast(`✗ Import error: ${error instanceof Error ? error.message : 'Unknown'}`, 'error');
    } finally {
      setIsImporting(false);
    }
  }, [parsedData, onImport, onClose, onShowToast]);

  // Copy template to clipboard
  const copyTemplate = useCallback(() => {
    navigator.clipboard.writeText(PROMPT_TEMPLATE);
    onShowToast('✓ Prompt template copied!', 'success');
  }, [onShowToast]);

  // Load example
  const loadExample = useCallback((exampleKey: keyof typeof EXAMPLES) => {
    const example = EXAMPLES[exampleKey];
    const json = JSON.stringify(example.data, null, 2);
    setJsonInput(json);
    handleJsonChange(json, true);
    onShowToast(`ℹ Loaded "${example.name}" example`, 'info');
  }, [handleJsonChange, onShowToast]);

  // Fix common issues
  const handleFixCommonIssues = useCallback(async () => {
    const { fixed, changes } = fixCommonJsonIssues(jsonInput);
    if (changes.length > 0) {
      setJsonInput(fixed);
      await handleJsonChange(fixed, true);
      setShowFixSuccess(true);
      onShowToast(`✓ Fixed ${changes.length} issue(s)`, 'success');
      setTimeout(() => setShowFixSuccess(false), 3000);
    } else {
      onShowToast('ℹ No common issues found', 'info');
    }
  }, [jsonInput, handleJsonChange, onShowToast]);

  // Copy error report
  const copyErrorReport = useCallback(() => {
    const report = {
      timestamp: new Date().toISOString(),
      category: validationState.category,
      errors: validationState.fieldErrors,
      inputPreview: jsonInput.substring(0, 500) + (jsonInput.length > 500 ? '...' : '')
    };
    navigator.clipboard.writeText(JSON.stringify(report, null, 2));
    setCopiedError(true);
    onShowToast('✓ Error report copied!', 'success');
    setTimeout(() => setCopiedError(false), 2000);
  }, [validationState, jsonInput, onShowToast]);

  // Calculate track statistics
  const trackStats = useMemo<TrackStats | null>(() => {
    if (!parsedData) return null;
    
    const stats: TrackStats = {
      totalNotes: 0,
      noteCounts: {},
      avgVelocity: 0,
      velocitySum: 0,
      noteCount: 0,
      duration: 0,
      // Automation stats
      automationLaneCount: 0,
      automationPointCount: 0,
      automatedParams: []
    };

    // Count notes in melodic tracks
    ['synthA', 'synthB', 'bass2'].forEach(track => {
      const trackData = parsedData.tracks[track as keyof typeof parsedData.tracks];
      if (trackData && 'notes' in trackData && Array.isArray(trackData.notes)) {
        const count = trackData.notes.length;
        stats.noteCounts[track] = count;
        stats.totalNotes += count;
        trackData.notes.forEach((note: { velocity?: number }) => {
          if (note.velocity) {
            stats.velocitySum += note.velocity;
            stats.noteCount++;
          }
        });
      }
    });

    // Count drum hits
    ['kick', 'snare', 'closedHat', 'openHat'].forEach(track => {
      const trackData = parsedData.tracks[track as keyof typeof parsedData.tracks];
      if (Array.isArray(trackData)) {
        const count = trackData.filter(Boolean).length;
        stats.noteCounts[track] = count;
        stats.totalNotes += count;
      }
    });

    // Count sampler notes
    if (parsedData.tracks.sampler) {
      parsedData.tracks.sampler.forEach((bank) => {
        const count = bank.steps.length;
        stats.noteCounts[`sampler${bank.bankIndex}`] = count;
        stats.totalNotes += count;
        bank.steps.forEach((note: { velocity?: number }) => {
          if (note.velocity) {
            stats.velocitySum += note.velocity;
            stats.noteCount++;
          }
        });
      });
    }

    stats.avgVelocity = stats.noteCount > 0 ? stats.velocitySum / stats.noteCount : 0;

    // Estimate duration
    const stepsPerPattern = 32;
    const secondsPerStep = 60 / parsedData.globals.tempo / 4;
    stats.duration = stepsPerPattern * secondsPerStep;

    // Count automation
    if (parsedData.automation && parsedData.automation.length > 0) {
      stats.automationLaneCount = parsedData.automation.length;
      parsedData.automation.forEach(lane => {
        const pointCount = lane.steps.filter(s => s !== null).length;
        stats.automationPointCount += pointCount;
        stats.automatedParams.push(`${lane.target}.${lane.parameter}`);
      });
    }

    return stats;
  }, [parsedData]);

  // Generate pattern grid for preview
  const patternGrid = useMemo(() => {
    if (!parsedData) return null;

    const tracks = ['synthA', 'synthB', 'bass2', 'kick', 'snare', 'closedHat', 'openHat', 'sampler0'];
    const grid: boolean[][] = [];

    tracks.forEach((trackName) => {
      const row: boolean[] = Array(32).fill(false);
      
      if (trackName === 'sampler0' && parsedData.tracks.sampler?.[0]) {
        parsedData.tracks.sampler[0].steps.forEach((note: { step: number }) => {
          if (note.step >= 0 && note.step < 32) row[note.step] = true;
        });
      } else if (trackName in parsedData.tracks) {
        const trackData = parsedData.tracks[trackName as keyof typeof parsedData.tracks];
        if (trackData && 'notes' in trackData && Array.isArray(trackData.notes)) {
          trackData.notes.forEach((note: { step: number }) => {
            if (note.step >= 0 && note.step < 32) row[note.step] = true;
          });
        } else if (Array.isArray(trackData)) {
          trackData.forEach((hit, i) => {
            if (i < 32 && hit) row[i] = true;
          });
        }
      }
      
      grid.push(row);
    });

    return { tracks, grid };
  }, [parsedData]);

  // Load preview with skeleton
  const loadPreview = useCallback(() => {
    if (!parsedData) return;
    setIsPreviewLoading(true);
    setTimeout(() => {
      setIsPreviewLoading(false);
    }, 500);
  }, [parsedData]);

  // Effect to load preview when switching to preview tab
  useEffect(() => {
    if (activeTab === 'preview' && parsedData) {
      loadPreview();
    }
  }, [activeTab, parsedData, loadPreview]);

  if (!isOpen) return null;

  const hasErrors = validationState.stage === 'error' && validationState.fieldErrors.length > 0;
  const isValid = validationState.stage === 'complete' && parsedData !== null;
  // @ts-expect-error - Auto-generated to fix CI build
  const textareaBorderColor = getTextareaBorderColor(validationState, jsonInput.trim().length > 0);

  const noteCountEntries = useMemo(() => {
    return trackStats ? Object.entries(trackStats.noteCounts) : [];
  }, [trackStats]);

  const trackStatisticsRows = useMemo(() => noteCountEntries.map(([track, count]) => (
    <div key={String(track)} className="flex items-center gap-2 text-xs">
      <span className="w-16 sm:w-20 text-gray-500 shrink-0">{String(track)}:</span>
      <div className="flex-1 h-2 bg-gray-800 rounded-full overflow-hidden">
        <div
          className="h-full bg-emerald-500/50 rounded-full transition-all duration-500"
          style={{ width: `${Math.min(100, (Number(count) / 16) * 100)}%` }}
        />
      </div>
      <span className="text-gray-400 w-6 sm:w-8 text-right shrink-0">{String(count)}</span>
    </div>
  )) as React.ReactElement[], [noteCountEntries]);

  return (
    <div 
      ref={modalRef}
      className="fixed inset-0 bg-black/70 backdrop-blur-sm z-50 flex items-center justify-center p-2 sm:p-4"
    >
      <div
        className="absolute inset-0 z-0"
        onClick={handleClose}
        aria-hidden="true"
      />
      <div 
        role="dialog"
        aria-modal="true"
        aria-labelledby="ai-song-modal-title" aria-describedby="ai-song-modal-desc"
        className="relative z-10 bg-[#0f1115] border border-emerald-500/30 rounded-xl shadow-[0_0_60px_rgba(16,185,129,0.2)] w-full max-w-3xl max-h-[95vh] sm:max-h-[90vh] flex flex-col animate-in fade-in zoom-in-95 duration-200"
        onDragEnter={handleDragEnter}
        onDragLeave={handleDragLeave}
        onDragOver={(e) => e.preventDefault()}
        onDrop={handleDrop}
      >
        {/* Header */}
        <div className="flex items-center justify-between p-3 sm:p-4 border-b border-gray-800">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 sm:w-10 sm:h-10 rounded-lg bg-emerald-500/10 border border-emerald-500/30 flex items-center justify-center">
              <span className="text-xl sm:text-2xl">🤖</span>
            </div>
            <div>
              <h2 id="ai-song-modal-title" className="text-base sm:text-lg font-bold text-white">Import AI Song</h2>
              <p id="ai-song-modal-desc" className="text-[10px] sm:text-xs text-gray-400 hidden sm:block">Import songs from Claude, Gemini, Jules, Copilot, etc.</p>
            </div>
          </div>
          <Tooltip text="Close (Esc)" position="bottom">
            <button 
              onClick={handleClose}
              className="w-8 h-8 rounded-lg bg-gray-800 hover:bg-gray-700 text-gray-400 hover:text-white transition-all"
              aria-label="Close modal"
              title="Close modal"
            >
              ✕
            </button>
          </Tooltip>
        </div>

        {/* Validation Status Bar */}
        <div className={`h-1 w-full transition-colors duration-300 ${getValidationColor(validationState.stage)} ${(validationState.stage === 'parsing' || validationState.stage === 'validating') ? 'animate-pulse' : ''}`}>
          <div 
            className="h-full bg-white/30 transition-all duration-300"
            style={{ width: `${validationState.progress}%` }}
          />
        </div>

        {/* Close Confirmation */}
        {showCloseConfirm && (
          <div className="px-4 py-2 bg-yellow-950/50 border-b border-yellow-900/50 flex items-center justify-between animate-in slide-in-from-top-2">
            <span className="text-xs text-yellow-400">You have unsaved changes. Close anyway?</span>
            <div className="flex gap-2">
              <button
                onClick={() => setShowCloseConfirm(false)}
                className="px-2 py-1 text-xs text-gray-400 hover:text-white transition-colors"
                aria-label="Cancel closing modal"
              >
                Cancel
              </button>
              <button
                onClick={confirmClose}
                className="px-2 py-1 text-xs bg-red-600 hover:bg-red-500 text-white rounded transition-colors"
                aria-label="Confirm close modal"
              >
                Close
              </button>
            </div>
          </div>
        )}

        {/* Tabs */}
        <div className="flex border-b border-gray-800 overflow-x-auto" role="tablist" aria-label="Import method">
          <button
            id="ai-modal-tab-paste"
            role="tab"
            aria-selected={activeTab === 'paste'}
            aria-controls="ai-modal-panel-paste"
            onClick={() => setActiveTab('paste')}
            className={`flex-1 py-2 sm:py-3 text-xs sm:text-sm font-medium transition-all whitespace-nowrap ${
              activeTab === 'paste'
                ? 'text-emerald-400 border-b-2 border-emerald-500 bg-emerald-500/5'
                : 'text-gray-400 hover:text-gray-200 hover:bg-gray-800/50'
            }`}
          >
            <span className="hidden sm:inline">📋 </span>Paste JSON
          </button>
          <button
            id="ai-modal-tab-template"
            role="tab"
            aria-selected={activeTab === 'template'}
            aria-controls="ai-modal-panel-template"
            onClick={() => setActiveTab('template')}
            className={`flex-1 py-2 sm:py-3 text-xs sm:text-sm font-medium transition-all whitespace-nowrap ${
              activeTab === 'template'
                ? 'text-emerald-400 border-b-2 border-emerald-500 bg-emerald-500/5'
                : 'text-gray-400 hover:text-gray-200 hover:bg-gray-800/50'
            }`}
          >
            <span className="hidden sm:inline">📝 </span>Template
          </button>
          <button
            id="ai-modal-tab-preview"
            role="tab"
            aria-selected={activeTab === 'preview'}
            aria-controls="ai-modal-panel-preview"
            onClick={() => isValid && setActiveTab('preview')}
            disabled={!isValid}
            className={`flex-1 py-2 sm:py-3 text-xs sm:text-sm font-medium transition-all whitespace-nowrap ${
              activeTab === 'preview'
                ? 'text-emerald-400 border-b-2 border-emerald-500 bg-emerald-500/5'
                : !isValid
                  ? 'text-gray-600 cursor-not-allowed'
                  : 'text-gray-400 hover:text-gray-200 hover:bg-gray-800/50'
            }`}
          >
            <span className="hidden sm:inline">👁️ </span>Preview
            {!isValid && <span className="text-[10px] opacity-50 ml-1">(needs valid JSON)</span>}
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-auto p-3 sm:p-4">
          {activeTab === 'paste' ? (
            <div id="ai-modal-panel-paste" role="tabpanel" aria-labelledby="ai-modal-tab-paste" className="space-y-4">
              {/* Example Buttons */}
              <div className="flex flex-col sm:flex-row sm:flex-wrap gap-2">
                <span className="text-xs text-gray-500 py-1 sm:py-2">Try with example:</span>
                <div className="flex flex-wrap gap-2">
                  {(Object.keys(EXAMPLES) as Array<keyof typeof EXAMPLES>).map(key => (
                    <Tooltip key={key} text={EXAMPLES[key].desc} position="bottom">
                      <button
                        onClick={() => loadExample(key)}
                        className="px-2 sm:px-3 py-1.5 bg-gray-800 hover:bg-gray-700 text-gray-300 text-xs rounded transition-all border border-gray-700 hover:border-emerald-500/50 flex items-center gap-1"
                      >
                        <span>{EXAMPLES[key].emoji}</span>
                        <span className="hidden sm:inline">{EXAMPLES[key].name.split(' ').slice(1).join(' ')}</span>
                        <span className="sm:hidden">{key === 'dnb' ? 'DnB' : key.charAt(0).toUpperCase() + key.slice(1)}</span>
                      </button>
                    </Tooltip>
                  ))}
                </div>
              </div>

              {/* Drop Zone */}
              <div
                onDragOver={(e) => { e.preventDefault(); }}
                className={`border-2 border-dashed rounded-lg p-4 sm:p-6 text-center transition-all duration-300 ${
                  isDragging 
                    ? 'border-emerald-500 bg-emerald-500/10 scale-[1.02] shadow-[0_0_30px_rgba(16,185,129,0.3)]' 
                    : 'border-gray-700 bg-gray-900/50 hover:border-gray-600'
                }`}
              >
                <div className={`text-3xl mb-2 transition-transform duration-300 ${isDragging ? 'scale-125 animate-bounce' : ''}`}>
                  {isDragging ? '📥' : '📁'}
                </div>
                <p className={`text-sm font-medium transition-all duration-300 ${isDragging ? 'text-emerald-400' : 'text-gray-400'}`}>
                  {isDragging ? 'Drop to import' : 'Drag & drop .json files here'}
                </p>
                <p className="text-xs text-gray-500 mt-1">
                  {isDragging ? 'Release to load' : 'Supports multiple files'}
                </p>
                <p className="text-xs text-gray-600 my-2">or</p>
                <Tooltip text="Select one or more .json files" position="bottom">
                  <button
                    onClick={() => fileInputRef.current?.click()}
                    className="px-4 py-2 bg-gray-800 hover:bg-gray-700 text-gray-300 text-xs rounded transition-all"
                  >
                    Browse Files
                  </button>
                </Tooltip>
                <input
                  ref={fileInputRef}
                  type="file"
                  accept=".json,application/json"
                  onChange={handleFileSelect}
                  multiple
                  className="hidden"
                />
                
                {/* Selected Files List */}
                {droppedFiles.length > 0 && (
                  <div className="mt-4 space-y-2">
                    <p className="text-xs text-gray-500 text-left">Selected files:</p>
                    {droppedFiles.map((droppedFile, index) => (
                      <div 
                        key={droppedFile.id} 
                        className={`flex items-center justify-between p-2 rounded-lg text-xs ${
                          index === 0 ? 'bg-emerald-500/10 border border-emerald-500/30' : 'bg-gray-800/50'
                        }`}
                      >
                        <div className="flex items-center gap-2 overflow-hidden">
                          <span>{getFileIcon(droppedFile.file.name)}</span>
                          <span className="text-gray-300 truncate">{droppedFile.file.name}</span>
                          <span className="text-gray-500 shrink-0">({formatFileSize(droppedFile.file.size)})</span>
                          {index === 0 && <span className="text-emerald-400 text-[10px]">(active)</span>}
                        </div>
                        <Tooltip text="Remove file" position="left">
                          <button
                            onClick={() => removeDroppedFile(droppedFile.id)}
                            className="w-6 h-6 rounded hover:bg-red-500/20 text-gray-500 hover:text-red-400 transition-all shrink-0"
                            aria-label={`Remove ${droppedFile.file.name}`}
                          >
                            ✕
                          </button>
                        </Tooltip>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {/* Textarea */}
              <div>
                <div className="flex items-center justify-between mb-2">
                  <label className="text-xs text-gray-500">Or paste JSON directly:</label>
                  <div className="flex items-center gap-2">
                    {/* Inline validation indicator */}
                    {validationState.stage !== 'idle' && (
                      <span className={`text-xs ${
                        validationState.stage === 'complete' ? 'text-emerald-400' :
                        validationState.stage === 'error' ? 'text-red-400' :
                        'text-yellow-400'
                      }`}>
                        {validationState.stage === 'complete' && '✓ Valid JSON'}
                        {validationState.stage === 'error' && `✗ ${validationState.fieldErrors.length} error(s)`}
                        {(validationState.stage === 'parsing' || validationState.stage === 'validating') && '⏳ Validating...'}
                      </span>
                    )}
                    <span className="text-xs text-gray-600">Ctrl+V to paste</span>
                  </div>
                </div>
                <textarea
                  ref={textareaRef}
                  value={jsonInput}
                  onChange={(e) => handleJsonChange(e.target.value)}
                  onKeyDown={(e) => {
                    // Allow Enter for new line, Ctrl+Enter for import
                    if (e.key === 'Enter' && (e.ctrlKey || e.metaKey) && parsedData) {
                      e.preventDefault();
                      handleImport();
                    }
                  }}
                  placeholder={`{\n  "meta": {\n    "title": "My AI Song",\n    "author": "claude",\n    "version": "1.0",\n    ...\n  }\n}`}
                  className={`w-full h-32 sm:h-40 bg-[#0a0c10] border ${textareaBorderColor} rounded-lg p-3 text-xs font-mono text-gray-300 resize-none focus:outline-none transition-colors duration-300`}
                  spellCheck={false}
                />
                {/* Keyboard hint */}
                {parsedData && (
                  <p className="text-[10px] text-emerald-500/70 mt-1 text-right">
                    Press Ctrl+Enter to import
                  </p>
                )}
              </div>

              {/* Validation Progress */}
              {validationState.stage !== 'idle' && validationState.stage !== 'error' && validationState.stage !== 'complete' && (
                <div className="flex items-center gap-2 text-xs text-yellow-400">
                  <span className="animate-spin">⏳</span>
                  <span>
                    {validationState.stage === 'parsing' && 'Checking JSON syntax...'}
                    {validationState.stage === 'validating' && 'Validating schema...'}
                    {validationState.stage === 'converting' && 'Converting to Hyphon format...'}
                  </span>
                </div>
              )}

              {/* Error Display */}
              {hasErrors && (
                <div className="p-4 bg-red-950/30 border border-red-900/50 rounded-lg animate-in fade-in slide-in-from-top-2">
                  <div className="flex items-center justify-between mb-2 flex-wrap gap-2">
                    <div className="flex items-center gap-2 text-red-400">
                      <span>⚠️</span>
                      <span className="text-sm font-medium">
                        {validationState.category === 'JSON_SYNTAX' && 'JSON Syntax Error'}
                        {validationState.category === 'SCHEMA_VIOLATION' && 'Schema Violation'}
                        {validationState.category === 'CONVERSION_ERROR' && 'Conversion Error'}
                        {validationState.category === 'NETWORK_ERROR' && 'Network Error'}
                      </span>
                    </div>
                    <div className="flex gap-2">
                      {validationState.category === 'JSON_SYNTAX' && (
                        <Tooltip text="Auto-fix common JSON issues" position="left">
                          <button
                            onClick={handleFixCommonIssues}
                            className="px-3 py-1 bg-red-900/50 hover:bg-red-800/50 text-red-300 text-xs rounded transition-all"
                            aria-label="Fix Common JSON Issues"
                          >
                            🔧 Fix Issues
                          </button>
                        </Tooltip>
                      )}
                      <Tooltip text="Copy error details to clipboard" position="left">
                        <button
                          onClick={copyErrorReport}
                          className="px-3 py-1 bg-gray-800 hover:bg-gray-700 text-gray-400 text-xs rounded transition-all"
                          aria-label="Copy error details to clipboard"
                        >
                          {copiedError ? '✓ Copied!' : '📋 Copy'}
                        </button>
                      </Tooltip>
                    </div>
                  </div>
                  
                  {showFixSuccess && (
                    <div className="mb-3 p-2 bg-emerald-900/30 border border-emerald-700/50 rounded text-emerald-400 text-xs animate-in fade-in">
                      ✓ Common issues fixed! Please review the changes.
                    </div>
                  )}

                  {/* Field-level errors with inline indicators */}
                  <div className="space-y-2 mt-3">
                    {validationState.fieldErrors.map((error, idx) => (
                      <div key={idx} className="text-xs p-2 bg-red-900/20 rounded border border-red-800/30">
                        <div className="flex items-start gap-2">
                          <span className="text-red-500 mt-0.5">●</span>
                          <div>
                            <div className="text-red-400 font-mono font-medium">{error.field}</div>
                            <div className="text-red-300/80">{error.message}</div>
                            {error.suggestion && (
                              <div className="text-gray-500 mt-1 flex items-center gap-1">
                                <span>💡</span>
                                <span>{error.suggestion}</span>
                              </div>
                            )}
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>

                  {/* Suggestions */}
                  {validationState.category && (
                    <div className="mt-3 pt-3 border-t border-red-900/30">
                      <p className="text-xs text-gray-500 mb-1">Suggestions:</p>
                      <ul className="text-xs text-gray-400 space-y-0.5 list-disc list-inside">
                        {getErrorSuggestions(validationState.category).map((suggestion, idx) => (
                          <li key={idx}>{suggestion}</li>
                        ))}
                      </ul>
                    </div>
                  )}
                </div>
              )}

              {/* Success Display */}
              {isValid && parsedData && (
                <div className="p-4 bg-emerald-950/30 border border-emerald-900/50 rounded-lg animate-in fade-in slide-in-from-top-2">
                  <div className="flex items-center gap-2 text-emerald-400 mb-3">
                    <span className="w-5 h-5 rounded-full bg-emerald-500/20 flex items-center justify-center text-xs">✓</span>
                    <span className="text-sm font-medium">Valid AI Song</span>
                  </div>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs">
                    <p className="flex justify-between sm:block">
                      <span className="text-gray-500">Title:</span> 
                        <span className="text-emerald-400/70 sm:ml-1">{String(parsedData.meta.title)}</span>
                    </p>
                    <p className="flex justify-between sm:block">
                      <span className="text-gray-500">Author:</span> 
                        <span className="text-emerald-400/70 sm:ml-1">{String(parsedData.meta.author)}</span>
                    </p>
                    <p className="flex justify-between sm:block">
                      <span className="text-gray-500">Tempo:</span> 
                        <span className="text-emerald-400/70 sm:ml-1">{String(parsedData.globals.tempo)} BPM</span>
                    </p>
                    <p className="flex justify-between sm:block">
                      <span className="text-gray-500">Generator:</span> 
                        <span className="text-emerald-400/70 sm:ml-1">{String(parsedData.meta.generator)}</span>
                    </p>
                    <p className="sm:col-span-2 flex flex-wrap gap-1">
                      <span className="text-gray-500">Tracks:</span> 
                      {Object.keys(parsedData.tracks).map(track => (
                        <span key={track} className="px-1.5 py-0.5 bg-emerald-500/10 rounded text-emerald-400/70 text-[10px]">
                          {track}
                        </span>
                      ))}
                    </p>
                    {parsedData.automation && parsedData.automation.length > 0 && (
                      <p className="sm:col-span-2 flex flex-wrap gap-1 items-center">
                        <span className="text-gray-500">Automation:</span> 
                        <span className="px-1.5 py-0.5 bg-cyan-500/10 rounded text-cyan-400/70 text-[10px]">
                            {String(parsedData.automation.length)} lane{parsedData.automation.length !== 1 ? 's' : ''}
                        </span>
                        {parsedData.automation.map((lane, idx) => (
                          <span key={idx} className="text-[10px] text-cyan-400/50">
                              {String(lane.target)}.{String(lane.parameter)}
                            {idx < parsedData.automation!.length - 1 ? ',' : ''}
                          </span>
                        ))}
                      </p>
                    )}
                  </div>
                </div>
              )}
            </div>
          ) : activeTab === 'template' ? (
            <div id="ai-modal-panel-template" role="tabpanel" aria-labelledby="ai-modal-tab-template" className="space-y-4">
              <div className="p-4 bg-gray-900/50 rounded-lg">
                <p className="text-sm text-gray-300 mb-4">
                  Copy this prompt template and paste it into your AI assistant (Claude, Gemini, Jules, Copilot, etc.).
                  Customize the genre, tempo, and mood as desired.
                </p>
                <Tooltip text="Copy to clipboard" position="right">
                  <button
                    onClick={copyTemplate}
                    className="mb-3 px-4 py-2 bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-medium rounded transition-all flex items-center gap-2"
                    aria-label="Copy AI Prompt Template"
                  >
                    <span>📋</span> Copy Template
                  </button>
                </Tooltip>
                <pre className="bg-[#0a0c10] border border-gray-800 rounded-lg p-4 text-xs text-gray-400 overflow-x-auto whitespace-pre-wrap font-mono">
                  {PROMPT_TEMPLATE}
                </pre>
              </div>
              
              <div className="p-4 bg-blue-950/20 border border-blue-900/30 rounded-lg">
                <h3 className="text-sm font-medium text-blue-400 mb-2">🎯 Tips for Best Results</h3>
                <ul className="text-xs text-blue-400/70 space-y-1 list-disc list-inside">
                  <li>Be specific about genre (techno, house, drum & bass, etc.)</li>
                  <li>Mention desired energy level (chill, driving, aggressive)</li>
                  <li>Reference specific artists or tracks for style</li>
                  <li>Specify complexity (minimal, layered, complex)</li>
                  <li>Most AIs work best with clear, structured prompts</li>
                </ul>
              </div>
            </div>
          ) : (
            /* Preview Tab */
            <div id="ai-modal-panel-preview" role="tabpanel" aria-labelledby="ai-modal-tab-preview" className="space-y-4">
              {isPreviewLoading ? (
                <PreviewSkeleton />
              ) : parsedData && trackStats && patternGrid ? (
                <div className="animate-in fade-in duration-300">
                  {/* Song Info */}
                  <div className="p-4 bg-gray-900/50 rounded-lg">
                    <h3 className="text-sm font-medium text-emerald-400 mb-3">{String(parsedData.meta.title)}</h3>
                    <div className="grid grid-cols-2 sm:grid-cols-3 gap-4 text-xs">
                      <div>
                        <span className="text-gray-500 block">Tempo</span>
                        <span className="text-white">{String(parsedData.globals.tempo)} BPM</span>
                      </div>
                      <div>
                        <span className="text-gray-500 block">Time Signature</span>
                        <span className="text-white">{String((parsedData.globals.timeSignature as any[]).join('/'))}</span>
                      </div>
                      <div>
                        <span className="text-gray-500 block">Swing</span>
                        <span className="text-white">{String(parsedData.globals?.swing ?? 0)}%</span>
                      </div>
                      <div>
                        <span className="text-gray-500 block">Est. Duration</span>
                        <span className="text-white">{String(trackStats.duration.toFixed(1))}s</span>
                      </div>
                      <div className="col-span-2 sm:col-span-1">
                        <span className="text-gray-500 block">Total Notes</span>
                        <span className="text-white">{String(trackStats.totalNotes ?? 0)}</span>
                      </div>
                    </div>
                  </div>

                  {/* Pattern Grid */}
                  <div className="p-4 bg-gray-900/50 rounded-lg">
                    <h3 className="text-sm font-medium text-gray-300 mb-3">Pattern Preview (8 tracks × 32 steps)</h3>
                    <div className="overflow-x-auto">
                      <div className="inline-block min-w-full">
                        {patternGrid.grid.map((row, trackIdx) => (
                          <div key={String(trackIdx)} className="flex items-center gap-1 mb-1">
                            <span className="w-16 sm:w-20 text-[10px] sm:text-xs text-gray-500 text-right mr-2 shrink-0">
                              {String(patternGrid.tracks[trackIdx])}
                            </span>
                            <div className="flex gap-0.5">
                              {row.map((active, stepIdx) => (
                                <Tooltip key={stepIdx} text={String(`Step ${stepIdx}`)} position="top">
                                  <div
                                    className={`w-1.5 h-3 sm:w-2 sm:h-4 rounded-sm transition-colors ${
                                      active 
                                        ? 'bg-emerald-500 shadow-[0_0_4px_rgba(16,185,129,0.5)]' 
                                        : stepIdx % 4 === 0 
                                          ? 'bg-gray-700' 
                                          : 'bg-gray-800'
                                    }`}
                                  />
                                </Tooltip>
                              ))}
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>

                  {/* Track Statistics */}
                  {trackStats ? (
                    <div className="p-4 bg-gray-900/50 rounded-lg">
                      <h3 className="text-sm font-medium text-gray-300 mb-3">{String("Track Statistics")}</h3>
                      <div className="grid grid-cols-2 gap-3 mb-3">
                        <div className="text-xs">
                          <span className="text-gray-500">{String("Total Events:")}</span>
                          <span className="text-white ml-2">{String(trackStats.totalNotes)}</span>
                        </div>
                        <div className="text-xs">
                          <span className="text-gray-500">{String("Avg Velocity:")}</span>
                          <span className="text-white ml-2">{String(Number.isNaN(Number(trackStats.avgVelocity)) ? '0' : (Number(trackStats.avgVelocity) * 100).toFixed(0))}%</span>
                        </div>
                      </div>
                      <div className="space-y-1.5">
                        {trackStats?.noteCounts ? (
                          (Object.entries(trackStats.noteCounts as Record<string, unknown>)).map(([track, count]) => {
                            const displayCount = typeof count === 'number' ? count : 0;
                            const progress = Math.min(100, (displayCount / 16) * 100);
                            return (
                              <div key={String(track)} className="flex items-center gap-2 text-xs">
                                <span className="w-16 sm:w-20 text-gray-500 shrink-0">{String(track)}:</span>
                                <div className="flex-1 h-2 bg-gray-800 rounded-full overflow-hidden">
                                  <div className="h-full bg-emerald-500/50 rounded-full transition-all duration-500" style={{ width: `${String(progress)}%` }} />
                                </div>
                                <span className="text-gray-400 w-6 sm:w-8 text-right shrink-0">{String(displayCount)}</span>
                              </div>
                            );
                          })
                        ) : null}
                      </div>
                      <div className="space-y-1.5">
                        {trackStatisticsRows.length > 0 && (trackStatisticsRows as React.ReactNode)}
                      </div>
                    </div>
                  ) : null}

                  {/* Automation Visualization */}
                  {trackStats.automationLaneCount > 0 && parsedData?.automation && (
                    <div className="p-4 bg-gray-900/50 rounded-lg">
                      <h3 className="text-sm font-medium text-gray-300 mb-3">
                        Automation ({trackStats.automationLaneCount} lanes, {trackStats.automationPointCount} points)
                      </h3>
                      <div className="space-y-3">
                        {parsedData.automation.map((lane, idx) => {
                          const nonNullSteps = lane.steps.map((v, i) => ({ value: v, step: i })).filter(s => s.value !== null);
                          const minVal = Math.min(...nonNullSteps.map(s => s.value!));
                          const maxVal = Math.max(...nonNullSteps.map(s => s.value!));
                          
                          return (
                            <div key={idx} className="bg-gray-800/50 rounded p-2">
                              <div className="flex items-center justify-between mb-2">
                                <div className="flex items-center gap-2">
                                  <span className="text-xs font-medium text-cyan-400">{lane.target}</span>
                                  <span className="text-xs text-gray-500">→</span>
                                  <span className="text-xs text-cyan-400/80">{lane.parameter}</span>
                                </div>
                                <div className="flex items-center gap-2 text-[10px] text-gray-500">
                                  <span className="px-1.5 py-0.5 bg-gray-700 rounded">{String(lane.interpolation || 'step')}</span>
                                  <span>{String(nonNullSteps.length)} pts</span>
                                  <span className="text-gray-600">|</span>
                                  <span>range: {String(minVal)}-{String(maxVal)}</span>
                                </div>
                              </div>
                              {/* Mini visualization bar */}
                              <div className="flex items-end gap-px h-8">
                                {lane.steps.map((value, stepIdx) => {
                                  const height = value !== null ? (value / 127) * 100 : 0;
                                  const isActive = value !== null;
                                  return (
                                    <div
                                      key={stepIdx}
                                      className={`flex-1 min-w-[2px] transition-all ${
                                        isActive 
                                          ? 'bg-cyan-500/60 hover:bg-cyan-400' 
                                          : 'bg-gray-700/30'
                                      }`}
                                      style={{ 
                                        height: isActive ? `${height}%` : '2px',
                                        opacity: stepIdx % 4 === 0 ? 1 : 0.7
                                      }}
                                      title={isActive ? `Step ${stepIdx}: ${value}` : `Step ${stepIdx}: (no change)`}
                                    />
                                  );
                                })}
                              </div>
                              {/* Step markers */}
                              <div className="flex mt-1">
                                {[0, 4, 8, 12, 16, 20, 24, 28].map(mark => (
                                  <div key={mark} className="flex-1 text-[8px] text-gray-600 text-center">
                                    {mark}
                                  </div>
                                ))}
                              </div>
                            </div>
                          );
                        })}
                      </div>
                      
                      {/* Automated Parameters Summary */}
                      <div className="mt-3 pt-3 border-t border-gray-800">
                        <p className="text-[10px] text-gray-500 mb-2">Automated Parameters:</p>
                        <div className="flex flex-wrap gap-1">
                          {trackStats.automatedParams.map((param, idx) => (
                            <span 
                              key={idx} 
                              className="px-2 py-0.5 bg-cyan-500/10 border border-cyan-500/20 rounded text-[10px] text-cyan-400"
                            >
                              {param}
                            </span>
                          ))}
                        </div>
                      </div>
                    </div>
                  )}

                  {/* Audio Preview */}
                  {audioEngine && (
                    <div className="p-4 bg-gray-900/50 rounded-lg">
                      <div className="flex items-center justify-between flex-wrap gap-2">
                        <div>
                          <h3 className="text-sm font-medium text-gray-300">Audio Preview</h3>
                          <p className="text-xs text-gray-500">Listen to the pattern before importing</p>
                        </div>
                        <Tooltip text="Coming soon!" position="left">
                          <button
                            className="px-4 py-2 bg-emerald-600 hover:bg-emerald-500 text-white text-sm font-medium rounded transition-all flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
                            onClick={() => onShowToast('Audio preview coming soon!', 'info')}
                            disabled
                            aria-label="Play Preview (Coming Soon)"
                          >
                            <span>▶</span> Play Preview
                          </button>
                        </Tooltip>
                      </div>
                    </div>
                  )}
                </div>
              ) : (
                /* Empty State */
                <div className="flex flex-col items-center justify-center py-12 text-center">
                  <div className="w-16 h-16 rounded-full bg-gray-800 flex items-center justify-center mb-4">
                    <span className="text-3xl">👁️</span>
                  </div>
                  <h3 className="text-sm font-medium text-gray-400 mb-2">No Preview Available</h3>
                  <p className="text-xs text-gray-600 max-w-xs">
                    Paste or drop valid JSON in the Paste tab to see a preview of your song.
                  </p>
                </div>
              )}
            </div>
          )}
        </div>

        {/* Progress Bar (shown during import) */}
        {isImporting && (
          <div className="px-4 py-3 border-t border-gray-800 bg-gray-900/30 animate-in slide-in-from-bottom-2">
            <div className="space-y-2">
              {importStages.map((stage) => (
                <div key={stage.name} className="flex items-center gap-3">
                  <div className="w-14 sm:w-16 text-[10px] sm:text-xs text-gray-500">{stage.name}</div>
                  <div className="flex-1 h-2 bg-gray-800 rounded-full overflow-hidden">
                    <div 
                      className={`h-full rounded-full transition-all duration-300 ${
                        stage.status === 'error' ? 'bg-red-500' :
                        stage.status === 'complete' ? 'bg-emerald-500' :
                        stage.status === 'active' ? 'bg-yellow-500 animate-pulse' :
                        'bg-gray-700'
                      }`}
                      style={{ width: `${stage.progress}%` }}
                    />
                  </div>
                  <div className="w-5 sm:w-6 text-xs">
                    {stage.status === 'complete' && <span className="text-emerald-500">✓</span>}
                    {stage.status === 'error' && <span className="text-red-500">✗</span>}
                    {stage.status === 'active' && <span className="text-yellow-500">⋯</span>}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Footer */}
        <div className="flex items-center justify-between p-3 sm:p-4 border-t border-gray-800">
          <div className="text-[10px] sm:text-xs text-gray-500 flex items-center gap-2">
            <span className={`
              w-2 h-2 rounded-full transition-colors duration-300
              ${validationState.stage === 'idle' ? 'bg-gray-600' : ''}
              ${(validationState.stage === 'parsing' || validationState.stage === 'validating') ? 'bg-yellow-500 animate-pulse' : ''}
              ${validationState.stage === 'converting' ? 'bg-emerald-500' : ''}
              ${validationState.stage === 'complete' ? 'bg-emerald-500' : ''}
              ${validationState.stage === 'error' ? 'bg-red-500' : ''}
            `} />
            <span className="hidden sm:inline">
              {validationState.stage === 'idle' && (jsonInput ? 'Waiting...' : 'Ready')}
              {validationState.stage === 'parsing' && 'Checking JSON syntax...'}
              {validationState.stage === 'validating' && 'Validating schema...'}
              {validationState.stage === 'converting' && 'Converting...'}
              {validationState.stage === 'complete' && '✓ Ready to import'}
              {validationState.stage === 'error' && `✗ ${validationState.fieldErrors.length} error(s)`}
            </span>
            <span className="sm:hidden">
              {validationState.stage === 'idle' && 'Ready'}
              {validationState.stage === 'parsing' && 'Parsing...'}
              {validationState.stage === 'validating' && 'Validating...'}
              {validationState.stage === 'converting' && 'Converting...'}
              {validationState.stage === 'complete' && '✓ Valid'}
              {validationState.stage === 'error' && '✗ Errors'}
            </span>
          </div>
          <div className="flex gap-2">
            <Tooltip text="Cancel (Esc)" position="top">
              <button
                onClick={handleClose}
                disabled={isImporting}
                className="px-3 sm:px-4 py-2 bg-gray-800 hover:bg-gray-700 text-gray-300 text-xs font-medium rounded transition-all disabled:opacity-50"
                aria-label="Cancel Import"
              >
                <span className="hidden sm:inline">Cancel</span>
                <span className="sm:hidden">✕</span>
              </button>
            </Tooltip>
            <Tooltip text={parsedData ? "Ctrl+Enter to import" : "Enter valid JSON first"} position="top">
              <button
                onClick={handleImport}
                disabled={!parsedData || isImporting}
                aria-busy={isImporting}
                className={`px-3 sm:px-4 py-2 text-xs font-medium rounded transition-all flex items-center gap-2 disabled:cursor-not-allowed ${
                  parsedData && !isImporting
                    ? 'bg-emerald-600 hover:bg-emerald-500 text-white shadow-[0_0_20px_rgba(16,185,129,0.3)] hover:shadow-[0_0_30px_rgba(16,185,129,0.5)]'
                    : 'bg-gray-700 text-gray-500'
                }`}
                aria-label="Import AI Song"
              >
                {isImporting ? (
                  <>
                    <span className="animate-spin">⏳</span>
                    <span className="hidden sm:inline">Importing...</span>
                  </>
                ) : (
                  <>
                    <span>🎵</span>
                    <span className="hidden sm:inline">Import Song</span>
                    <span className="sm:hidden">Import</span>
                  </>
                )}
              </button>
            </Tooltip>
          </div>
        </div>
      </div>
    </div>
  );
});

export default AISongModal;
