import type { PropertyChangeKey } from "./types";

export interface SynthEffectPropertiesProps {
  trackType: "synth" | "drum" | "voice";
  onPropertyChange: (key: PropertyChangeKey, value: number | boolean | string | number[]) => void;
  isProphecy?: boolean;
  currentFreeze?: number;
  currentFreezeLfoSync?: boolean;
  currentFreezeLfoRate?: number;
  currentFreezeLfoDepth?: number;
  currentFreezeEnvDepth?: number;
  currentGrainEnvDepth?: number;
  currentGrainPitchEnvDepth?: number;
  currentGrainLfoRate?: number;
  currentGrainLfoDepth?: number;
  currentGrainJitter?: number;
  currentGrainPitchQuantize?: number;
  currentGranularPitchShift?: number;
  currentWindowShape?: number;
  currentCustomGrainEnvelope?: number[];
  currentVocoderMix?: number;
  currentVocoderFormantShift?: number;
  currentVocoderPreservation?: number;
  currentBitcrush?: number;
  currentSpectralComp?: number;
  currentDownsample?: number;
  currentSpectralCompression?: number;
  currentTranceGate?: number;
  currentFormantShift?: number;
  currentFormantPitchLink?: number;
  currentSlideFormant?: boolean;
  currentFormantLfoSync?: boolean;
  currentFormantLfoRate?: number;
  currentFormantLfoDepth?: number;
  currentTremoloRate?: number;
  currentTremoloDepth?: number;
  currentPitchAmount?: number;
  currentPitchAttack?: number;
  currentPitchDecay?: number;
  currentFormantEnvSync?: boolean;
  currentFormantEnvAttack?: number;
  currentFormantEnvDecay?: number;
  currentFormantEnvAmount?: number;
  currentFormantEnvFollower?: number;
  currentFormantSidechainDepth?: number;
  currentDrive?: number;
  currentVibratoDepth?: number;
  currentVowel?: number;
  currentPortamento?: number;
  currentCharacterMorph?: number;
  currentFilterCutoff?: number;
  currentFilterResonance?: number;
  currentEnvMod?: number;
  currentRetrigger?: number;
  currentTimeStretchEnvDepth?: number;
  currentSpectralPanRate?: number;
  currentSpectralPanDepth?: number;
  currentReverse?: boolean;
  currentCustomWindowShape?: number[];
  currentVolumeFilterMod?: number;
}
