/**
 * Shared harness for the singing-voice FX golden (integration) and perf tiers:
 * loads the real public/rubberband.wasm, builds a deterministic vocal-like
 * signal, and drives a VocalFxChain block by block like the worklet does.
 */

import { readFileSync } from 'node:fs';
import { join } from 'node:path';
// @ts-ignore - generated by emscripten/build_rubberband.sh
import createRubberBandModule from '@/audio-worklets/rubberband-lib.js';
import { repoRoot, requireRepoArtifacts } from './requireRepoArtifacts';
import {
  probeNativeVocalFx,
  type RubberBandFxModule,
} from '@/audio-worklets/rubberband/nativeVocalFx';
import {
  createVocalFxBlock,
  type VocalFxBlock,
  type VocalFxChain,
} from '@/audio-worklets/rubberband/vocalFx';

export const RUBBERBAND_ARTIFACTS = [
  'public/rubberband.wasm',
  'src/audio-worklets/rubberband-lib.js',
] as const;

export const QUANTUM = 128;

export async function loadRubberBandFxModule(): Promise<RubberBandFxModule & { _malloc(n: number): number }> {
  requireRepoArtifacts(RUBBERBAND_ARTIFACTS);
  const wasmBinary = readFileSync(join(repoRoot(), 'public/rubberband.wasm'));
  const module = await createRubberBandModule({ wasmBinary });
  const probe = probeNativeVocalFx(module);
  if (!probe.ok) {
    throw new Error(`${probe.reason} — rebuild with: pnpm run build:wasm:rubberband`);
  }
  return module as RubberBandFxModule & { _malloc(n: number): number };
}

/**
 * JS twin of RbFx::random() in emscripten/rubberband_fx.cpp (xorshift32,
 * 24-bit [0, 1)). Seeding the TS oracle with this and NativeVocalFx with the
 * same seed makes jitter and pan spread comparable sample for sample.
 */
export function xorshift32(seed: number): () => number {
  let x = seed >>> 0;
  return () => {
    x = (x ^ (x << 13)) >>> 0;
    x = (x ^ (x >>> 17)) >>> 0;
    x = (x ^ (x << 5)) >>> 0;
    return (x >>> 8) / 16777216;
  };
}

/**
 * ~220 Hz voiced tone (8 harmonics, 5 Hz vibrato) under a 4 Hz syllable
 * envelope, with a noise "consonant" burst at each syllable onset.
 */
export function makeVocalSignal(sampleRate: number, seconds: number, seed = 1234): Float32Array {
  const n = Math.floor(sampleRate * seconds);
  const out = new Float32Array(n);
  const noise = xorshift32(seed);
  let phase = 0;
  for (let i = 0; i < n; i++) {
    const t = i / sampleRate;
    const f0 = 220 * Math.pow(2, (30 / 1200) * Math.sin(2 * Math.PI * 5 * t));
    phase += (2 * Math.PI * f0) / sampleRate;
    let voiced = 0;
    for (let k = 1; k <= 8; k++) voiced += Math.sin(k * phase) / k;
    const syllable = (t * 4) % 1;
    const env = Math.min(1, syllable / 0.05) * Math.exp(-2.5 * syllable);
    const burst = syllable < 0.03 ? (noise() * 2 - 1) * 0.4 : 0;
    out[i] = 0.35 * voiced * env + burst;
  }
  return out;
}

export interface FxCase {
  name: string;
  block: Partial<VocalFxBlock>;
}

/** Representative "FX on" vocal settings (perf tier + combined golden case). */
export const FX_ON_BLOCK: Partial<VocalFxBlock> = {
  hasPhonemeContext: true,
  phonemeVolume: 0.8,
  isVowel: 1,
  phonemeFilterMod: 0.6,
  volumeFilterMod: 0.4,
  syllableVolume: 0.7,
  gateDepth: 0.5,
  gateRate: 8,
  spectralComp: 0.6,
  grainPanSpread: 0.5,
  vocalChorus: 0.5,
  subHarmonics: 0.4,
  duckingScalar: 0.2,
  drumIsSnare: 1,
};

export function blockFor(overrides: Partial<VocalFxBlock>): VocalFxBlock {
  return Object.assign(createVocalFxBlock(), overrides);
}

/** Runs `signal` through `chain.process` quantum by quantum; returns [L, R]. */
export function runChain(
  chain: VocalFxChain,
  signal: Float32Array,
  block: VocalFxBlock,
): [Float32Array, Float32Array] {
  const blocks = Math.floor(signal.length / QUANTUM);
  const outL = new Float32Array(blocks * QUANTUM);
  const outR = new Float32Array(blocks * QUANTUM);
  const left = new Float32Array(QUANTUM);
  const right = new Float32Array(QUANTUM);
  for (let b = 0; b < blocks; b++) {
    left.set(signal.subarray(b * QUANTUM, (b + 1) * QUANTUM));
    right.fill(0);
    chain.process(block, left, right);
    outL.set(left, b * QUANTUM);
    outR.set(right, b * QUANTUM);
  }
  return [outL, outR];
}

export interface ErrorStats {
  maxAbs: number;
  /** Reference energy over error energy, dB (Infinity when identical). */
  snrDb: number;
}

export function compareSignals(reference: Float32Array, candidate: Float32Array): ErrorStats {
  let maxAbs = 0;
  let refEnergy = 0;
  let errEnergy = 0;
  for (let i = 0; i < reference.length; i++) {
    const e = candidate[i] - reference[i];
    if (!Number.isFinite(candidate[i])) return { maxAbs: Infinity, snrDb: -Infinity };
    maxAbs = Math.max(maxAbs, Math.abs(e));
    refEnergy += reference[i] * reference[i];
    errEnergy += e * e;
  }
  const snrDb = errEnergy === 0 ? Infinity : 10 * Math.log10((refEnergy || 1e-30) / errEnergy);
  return { maxAbs, snrDb };
}
